### ISSUE TITLE
Images will not load

### ISSUE THREAD

**Issue by darienurse** [Adamantcheese/Kuroba#1430] opened 2023-06-10 14:27 UTC
![image](https://github.com/Adamantcheese/Kuroba/assets/2359072/17f9231d-7850-47a2-8b4e-299a261142dc)

Seemingly random images will not load, with this unreadable error popping up when you open them.

Opening the images in the browser they load fine so it shouldn't be a 4chan problem.

**Comment by Adamantcheese** [comment] 2023-06-10 21:35
Duplicate of #1425. Use the latest version of dev or disable the concurrent stuff on release.

**Closed as completed by Adamantcheese** 2023-06-10 21:35 UTC
