### ISSUE TITLE
support for soundposts

### ISSUE THREAD

**Issue by AllesWasTaken** [Adamantcheese/Kuroba#1254] opened 2021-05-12 11:04 UTC
Is possible to add support to soundposts?
Soundposts are webm images with a link to a MP3 file in the filename of the webm

Example:
https://i.4cdn.org/vt/1620772685965.png

Still_into_you[sound=files.catbox.moe%2Fojai4u.m4a].webm

**Comment by Adamantcheese** [comment] 2021-05-13 06:59
Duplicate of #888. I'll leave this up for now though, almost a year to date since that one was posted.

**Comment by ghost** [comment] 2021-05-16 07:01
It would be kinda cool to have this, or maybe at least the ability to jump to links that are in filenames

**Closed as completed** 2021-05-17 04:12 UTC
Labels: duplicate, enhancement
