### ISSUE TITLE
Report "[math]"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1013] opened 2020-07-28 08:16 UTC
UUID: 96c7785ed42d977af3aa2788bc42690d
Build flavor: stable
Version name: v4.13.5
OS info: Android 8.0.0, sdk version: 26
Report description: [math] only displays the code itself instead of the desired output, rendering it useless

**Comment by Adamantcheese** [comment] 2020-07-29 01:06
Duplicate of #404.

**Closed as completed by Adamantcheese** 2020-07-29 01:06 UTC
Labels: duplicate, report/crash report
