### ISSUE TITLE
Crash report "java.lang.ArithmeticException: divide by zero"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#861] opened 2020-04-26 08:31 UTC
UUID: a633727bd2de4ffaa55d125dbb6f8d17
Build flavor: stable
Version name: v4.11.1
OS info: Android 7.0, sdk version: 24
Report description: No title
=== STACKTRACE ===
```
Called from unhandled exception handler.
java.lang.ArithmeticException: divide by zero
	at com.github.adamantcheese.chan.core.site.http.ProgressRequestBody$ProgressSink.write(ProgressRequestBody.java:86)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:184)
	at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
	at com.github.adamantcheese.chan.core.site.http.ProgressRequestBody.writeTo(ProgressRequestBody.java:62)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
```

**Comment by K1rakishou** [comment] 2020-04-26 08:31
Maybe it's already fixed, but I don't remember it getting fixed.

**Comment by Adamantcheese** [comment] 2020-04-27 06:09
Duplicate of #717.

**Closed as completed by Adamantcheese** 2020-04-27 06:09 UTC
Labels: bug, duplicate, report/crash report
