### ISSUE TITLE
[Feature Request] Import list of filters

### ISSUE THREAD

**Issue by gliffs** [Adamantcheese/Kuroba#1065] opened 2020-08-16 03:38 UTC
If this is already a feature and I just haven't noticed then I apologize, but uh if this isn't a thing yet it'd be super convenient if I could import a list of filters somehow. Even more so if I was able to quickly import my existing 4chan-x filters.

**Comment by Adamantcheese** [comment] 2020-08-16 04:50
Duplicate of #363.

**Closed as completed by Adamantcheese** 2020-08-16 04:50 UTC
Labels: duplicate
