### ISSUE TITLE
Cannot jump to reply if it's just a link

### ISSUE THREAD

**Issue by zetapulse** [Adamantcheese/Kuroba#795] opened 2020-03-04 07:37 UTC
Looking through the replies to a post, there was one that was just a post link (eg >>542555). I tried to jump to it by fine-tapping it, however:
1) double-rapping the info section did nothing.
2) double tapping the remaining empty space to the side of the link would activate said link.

**Comment by Adamantcheese** [comment] 2020-03-04 08:20
Duplicate of #776. Should be fixed next release, or dev right now.

**Closed as completed by Adamantcheese** 2020-03-04 08:20 UTC
Labels: duplicate
