### ISSUE TITLE
Wrong thread sometimes opens

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#946] opened 2020-06-26 02:49 UTC
I think the app has a tendency to open recently opened threads instead of the one you tap on.
Just now I tried to open a thread in board mode and instead I got one that wasn't even on screen, and I had to scroll down quite a ways to find it. I did have the thread bookmarked, but it wasn't the thread I had open in split mode.

I'm using v4.12.0-d13de9f on a Samsung Note 10 Plus.

**Comment by Adamantcheese** [comment] 2020-06-26 05:52
Guess whenever it crops up again I'd like some more info.

**Comment by ghost** [comment] 2020-06-27 04:24
I have no idea what causes it, but I really don't know how this could happen without some weird bug. If I had to guess, it would be that the thread stays highlighted as if you're still tapped on it when you go to the next thread and then it opens instead (or maybe after?).
I'm saying this because the same thing happened just now and the thread I wanted to open was highlighted, but so was the last thread I had tapped on.

**Comment by ghost** [comment] 2020-06-27 04:33
Hmm, maybe I'm somehow tapping on two threads at the same time and recently opened threads aren't the main cause. Though maybe you're able to tap on a thread and a previous thread somehow.
In any case, it is possible to open two threads at once and not get the one you wanted, but that only explains half of my problem. Or I could just be crazy

**Comment by Adamantcheese** [comment] 2020-06-27 05:02
Still can't reproduce it. Tapping two threads at once doesn't seem to cause any problems in _slide mode_. It might be a problem specific to _split mode_ like how you've described if you tap two threads at the same time. Also it might be a problem if the site you're talking about is 2ch.hk, because that site has some serious API issues, although I don't think you're using that site.

I'll take a look at how cells get highlighted and try to figure out a reproduction method as well, since you said two threads in board mode were highlighted. Usually only one thread will be highlighted once you tap on it, unless you've made some other thread since all posts made by you are highlighted.

**Comment by Adamantcheese** [comment] 2020-06-27 05:39
Update, can't cause it to happen in slide mode either, at least for 4chan. Highlighting doesn't lead me to any situations that would point me to a root cause. You're probably doing something strange, but I'll keep this open if you find a better method of reproduction. You can close the issue yourself if there's no actual bug, but otherwise I'll probably close this one out in a month's time or so.

**Comment by Adamantcheese** [comment] 2020-06-27 07:00
Okay, so I did have it happen to me once, and the thread that reappeared was one that I had recently unpinned.

**Comment by Adamantcheese** [comment] 2020-06-27 07:17
I know the cause issue and will fix it and release an update shortly.

**Closed as completed** 2020-06-27 07:23 UTC
Labels: bug

**Comment by ghost** [comment] 2020-06-27 20:51
Nice job figuring that out.
