### ISSUE TITLE
Webm freezing the app with android 10

### ISSUE THREAD

**Issue by khezuu** [Adamantcheese/Kuroba#540] opened 2020-01-31 22:27 UTC
Hello,

my nokia 6.1 got the android 10 update recently and now webms freeze the app for serval seconds.

they play fine but when you attempt to close them or switch to the next webm the app freezes for serval seconds before continuing.

I tried clearing the cache and reinstalling the app but nothing helps, the same problem occurs in clover so i thought maybe its the android version.

**Comment by Adamantcheese** [comment] 2020-01-31 22:53
Unfortunately, if the problem exists in Clover as well as Kuroba, there's not much I can do to help, as the WebM library used is exactly the same; your phone is definitely more than powerful enough to do any video streaming. In the next release WebM streaming is returning, so that may solve your problem?

**Comment by K1rakishou** [comment] 2020-02-01 06:08
We could also try to update the exoplayer.

**Comment by Adamantcheese** [comment] 2020-02-01 06:15
I'll do that, we're a few versions behind.

**Comment by K1rakishou** [comment] 2020-02-01 06:17
Hopefully it will help.

**Comment by Adamantcheese** [comment] 2020-02-01 06:22
I've pushed a bunch of stuff just now, so the dev version should be updated soon if that can be tried out real fast.

**Comment by K1rakishou** [comment] 2020-02-01 06:27
Alright, gonna play around with it a little bit. What about the gestures, though?

**Comment by Adamantcheese** [comment] 2020-02-01 06:38
I'll wait on that until the next release to have it sorta be the "feature" for that one.

**Comment by K1rakishou** [comment] 2020-02-01 06:39
Damn, they are so addictive that it's just not the same without them.

**Comment by K1rakishou** [comment] 2020-02-01 06:43
How about merging them right after the release?

**Comment by Adamantcheese** [comment] 2020-02-01 06:44
I left a comment in the PR, let's move this conversation there.

**Comment by khezuu** [comment] 2020-02-01 07:43
Just checked the dev build and the problem persists. The webms play fine but i cannot swipe to the next webm or close it without the app freezing for 4 seconds.

But what i noticed it when swiping to a new webm, the app will freeze but download the new webm while in the frozen state, so when it unfreezes the new webm instantly plays.

**Comment by K1rakishou** [comment] 2020-02-01 08:05
@khezuu Do you have webm streaming turned on?

**Comment by Adamantcheese** [comment] 2020-02-01 08:12
I think I might have something that should help it out actually. Give me a bit.

**Comment by Adamantcheese** [comment] 2020-02-01 08:39
Once that dev build is ready, try that.

**Comment by K1rakishou** [comment] 2020-02-01 08:50
I think it broke webm streaming.

**Comment by K1rakishou** [comment] 2020-02-01 08:51
Yeah, it did.

**Comment by K1rakishou** [comment] 2020-02-01 08:53
Request canceling was already working by the way. The only difference is that it was canceling not the previous/next image (-1/+1) but current image -2/+2

**Comment by Adamantcheese** [comment] 2020-02-01 08:55
Hm, well I'll revert the change then, but it's likely out of the scope of Kuroba.

**Comment by K1rakishou** [comment] 2020-02-01 08:57
@khezuu can you also try the previous release (https://github.com/Adamantcheese/Kuroba/releases/tag/v4.10.2) and see if it's better or not.

**Comment by khezuu** [comment] 2020-02-01 09:20
It doesn't work there either. I just did a factory reset of the phone just for the heck of it but the problem is still there.

Guess android 10 broke something for me.

**Comment by K1rakishou** [comment] 2020-02-01 09:22
>It doesn't work there either

Welp, then it's probably something in how your phone decodes the videos or exoplayer bug. Try opening a couple of webms in the browser and see how they work. Though you did say that it was the same in Clover so I should have figured out that it won't work in the previous release either.

**Comment by K1rakishou** [comment] 2020-02-01 09:24
Do you use any customs ROMs?

**Comment by khezuu** [comment] 2020-02-01 09:33
No custom roms, in chrome everything is normal and as fast as i can press buttons.

**Comment by K1rakishou** [comment] 2020-02-01 09:46
Alright, one last thing. Can you play a couple of webms and post the logs here. Maybe there will be some exoplayer errors or something like that. Or you can just send them as a report (it's in the settings).

**Comment by Adamantcheese** [comment] 2020-02-01 09:53
[If it's a bug on exoplayer's part, probably a good idea to report it there.](https://github.com/google/ExoPlayer/issues)

**Comment by K1rakishou** [comment] 2020-02-01 09:58
Well without at least the logs they won't even consider looking into it.

**Comment by khezuu** [comment] 2020-02-01 10:02
`E/Kuroba-dev | MultiImageView: getWidth() or getHeight() returned 0, not loading
E/Kuroba-dev | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba-dev | MultiImageView: getWidth() or getHeight() returned 0, not loading
E/Kuroba-dev | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba-dev | MultiImageView: getWidth() or getHeight() returned 0, not loading
`

This is the only thing i noticed wrong (I also sent a full log right now).

But I managed to further identify the problem. The problem seems to specifically to close a webm.

If I for example swipe from an webm to a gif file the freeze also happens! (even tho gif swiping works fine)

The app has to wait for the webm to close in order to show the next image or webm and this is where the freeze happens.

**Comment by K1rakishou** [comment] 2020-02-01 10:05
Yeah, I just figured out that we do not collect all the logcat logs, only Kuroba logs, so even if there is something related to exoplayer we won't see it.

**Comment by K1rakishou** [comment] 2020-02-01 10:48
Welp, I tried to reproduce this thing for quite some time, but it just works for me. The only strange thing here is this log:
```
AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
```

I didn't see it at all while testing it. And I wonder how can it even happen.

**Comment by khezuu** [comment] 2020-02-01 11:13
This is not a related issue I believe. I guess the app has to wait for exoplayer to close the webm stream before it can continue showing the next one and this causes for me a freeze after the android update.

If it somehow could do it in the background without freezing the app that would be great but if its only me having the issue maybe its device specific or not enough people are on the latest android version yet.

**Comment by K1rakishou** [comment] 2020-02-01 11:17
I think I found something similar in Clover issues: https://github.com/chandevel/Clover/issues/755

**Comment by K1rakishou** [comment] 2020-02-01 11:21
@khezuu We can't use a background thread to release the ExoPlayer because there is an explicit check in the release() method that clearly says that it should only be called on the main thread.

![image](https://user-images.githubusercontent.com/10332458/73591297-f5d4cc80-44fd-11ea-9a3a-83b4a6d4e967.png)

**Comment by K1rakishou** [comment] 2020-02-01 11:23
I guess it's possible that the cause of the problem is us releasing and instantiating the player on every swipe. I think we should actually move it one layer up so we can just reuse it instead of recreating it every time. I guess somewhere inside ImageViewerController?

**Comment by khezuu** [comment] 2020-02-01 11:23
Oh great news I guess, If more people on Android 10 have the issue maybe it will get solved in the future by exo

**Comment by K1rakishou** [comment] 2020-02-01 11:58
@khezuu So I've moved the ExoPlayer instantiation to a different place, so we don't have to recreate it on every swipe, here is the apk:
[Kuroba-8fbf1f6.zip](https://github.com/Adamantcheese/Kuroba/files/4142498/Kuroba-8fbf1f6.zip)

Please try it and leave the feedback.

**Comment by khezuu** [comment] 2020-02-01 12:15
Just checked it out, when i swipe once the app wont freeze but it will show a blank video instead (Timer 00:00). If I swipe again now the app will freeze and then show a working webm again. 

webm>blank>freeze/webm>blank>freeze/webm, basically skipping every second webm

Attempting to use the back button to close the webm however will guarantee to freeze again. **<<** And this is the crtitical part, if we fix this issue then the swiping will work again too.

**Comment by K1rakishou** [comment] 2020-02-01 12:35
>but it will show a blank video instead (Timer 00:00)

Sometimes it will take some time for a video to load because of shitty 4chan servers so it's normal. It should load eventually. Turn off webm streaming if you want to see the loading bar(s).

>webm>blank>freeze/webm>blank>freeze/webm, basically skipping every second webm

That's really strange. If it's still freezing when swiping then releasing ExoPlayer has nothing to do with it.

**Comment by K1rakishou** [comment] 2020-02-07 08:52
~~@khezuu 
Do you use SAF by the way and if you do do you store your files on a sd-card?~~

Actually nevermind, I forgot that it's the same in Clover and Clover has no SAF support yet.

**Comment by khezuu** [comment] 2020-02-10 12:17
External players work fine by the way (mxplayer) but of course not as handy as just swiping trough webms.

**Comment by K1rakishou** [comment] 2020-02-10 12:34
Then it's definitely something wrong with Exoplayer and it's probably device-specific.

**Comment by K1rakishou** [comment] 2020-02-10 12:36
I guess we could try adding mpv as an alternative to exoplayer but it won't be easy. And it will make apk larger by a lot. (mpv-android weighs 23MB - https://github.com/mpv-android/mpv-android/releases I guess because of ffmpeg and other stuff). Oh and it's in pre-release state.

**Comment by Adamantcheese** [comment] 2020-02-11 02:17
As the issue occurs now as a result of an Android 10 upgrade where it did not occur previously, it is likely the result of that upgrade. It may also be related to this issue https://github.com/google/ExoPlayer/issues/4352, but also I'm seeing a lot of bug reports of a "black screen" for Nokia 6.1's with Android 10. As this is not an application issue, I'm going to close this issue. Replacing the player that works for 99% of people is a waste of effort for something that was caused by the OS OEM vendor.

**Closed as completed by Adamantcheese** 2020-02-11 02:17 UTC
Labels: cantfix

**Comment by Astridchan** [comment] 2020-02-11 22:49
FYI, saw this in a review for another 4chan client app.

![Screenshot_20200212-004611~2](https://user-images.githubusercontent.com/40862101/74286870-64e9c680-4d31-11ea-927b-0302c5ea0203.jpg)

**Comment by shad00m** [comment] 2020-04-25 23:39
I just got switched from Android 9 to android 10 on a Nokia 8 sirocco.
It was fine on Android 9 but as everyone else mentioned swiping through WebMs freezes the whole phone for like 5 seconds. Anyone knows of there's a workaround as it seems to be a Nokia issue?

**Comment by Adamantcheese** [comment] 2020-04-27 06:11
@shad00m You're not going to get much response on a closed issue for a small project for a specific set of devices. You'd be better off complaining to Nokia asking why their hardware decoder is fucked.
