### ISSUE TITLE
Error posting

### ISSUE THREAD

**Issue by Soundtoxin** [Adamantcheese/Kuroba#1450] opened 2024-01-10 16:48 UTC
Since a few days ago, when I try to post, it just tells me "Error posting". I'm logged into my pass, I'm not banned. I updated to the latest dev version, which didn't help.

**Comment by Adamantcheese** [comment] 2024-01-12 02:34
I don't know if this is new or anything, you've posted almost no information so I'll just assume it's a dupe of https://github.com/Adamantcheese/Kuroba/issues/1448.

**Closed as not planned by Adamantcheese** 2024-01-12 02:34 UTC
Labels: duplicate

**Comment by Soundtoxin** [comment] 2024-01-12 02:46
Are you saying the captcha is the problem even when using a pass?
The error itself is generic (it said what I said, I agree it was lacking info), not sure what other info to supply. Latest dev build updated via the app.

OnePlus 8T (Kebab) running LineageOS 20 (Android 13)

I was trying to post on /g/ at the time. What else do you need to know? Is there a relevant log to grab somewhere?

**Comment by Twinov** [comment] 2024-01-12 03:16
Believe you still have to pass the Cloudflare check to post with a pass.
