### ISSUE TITLE
App has been crashing far more than normal

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1268] opened 2021-05-20 05:18 UTC
I get a crash more than once per hour, normally when I tap on a new thread or image.

Tested on v4.13.6-2504fc8 on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment] 2021-05-21 01:29
Sorry clawyf, but saying "it's crashing" and posting no logs is going to make me close this issue for the time being. I'll keep it in the back of my head, but it's not enough info to troubleshoot on.

**Comment by ghost** [comment] 2021-05-21 04:06
> Sorry clawyf, but saying "it's crashing" and posting no logs is going to make me close this issue for the time being. I'll keep it in the back of my head, but it's not enough info to troubleshoot on.

I totally get that, it just doesn't seem like logs are getting saved so I'm not sure what to do.
In any case, the app will always crash if you submit a report and go back into the board menu.

**Comment by Adamantcheese** [comment] 2021-05-21 04:08
I'll take that, that's at least some reproduction steps I can investigate.

**Comment by ghost** [comment] 2021-05-21 04:14
> I'll take that, that's at least some reproduction steps I can investigate.

Cool. It also applies to submitting a report and opening a thread if you were in the board menu first.
It doesn't seem to be related to the crashes I got when opening images.

**Comment by Adamantcheese** [comment] 2021-05-21 06:19
So I can't reproduce your issue either on emulator or on my OnePlus 6, but maybe those changes will fix it? I'm thinking that whatever WebView implementation your device has is doing some strange stuff, or it could be that because of animation delay some stuff is failing. I'll have to ask you to help me debug this a little bit and if it doesn't end up working out then I'll just go ahead and implement an in-app report window instead of a webview.

**Comment by ghost** [comment] 2021-05-21 08:20
Cool, the report issue seems to be gone. I will tell you if I experience other crashes, but this is cool.
Also I realized the app was crashing even if I didn't go to a different window, I just wasn't waiting long enough at first. So my crashing issues may all be solved.

**Comment by Adamantcheese** [comment] 2021-05-21 20:08
Sweet, thanks for the update.

**Closed as completed by Adamantcheese** 2021-05-21 20:08 UTC
Labels: report/crash report
