### ISSUE TITLE
[BUG] Catalog/thread loading becomes unbearably slow at seemingly random times

### ISSUE THREAD

**Issue by powerLien** [Adamantcheese/Kuroba#286] opened 2019-08-09 03:39 UTC
I wish I knew a way to reliably reproduce this, but sometimes, it seems as if a switch is flipped, and reloading the catalog or loading a new thread becomes unbearably slow (taking up to 30 seconds). After a thread loads in, new thumbnails also seem to take a long time to load in (up to a few minutes in some instances). Additionally, if I am swiping through images and attempt to exit image viewing mode on any image except the image I started swiping on, Kuroba will display the thumbnail version of the first image I viewed while swiping, and I will be unable to exit image viewing mode in any way except closing and reopening the app. This issue always appears in concert with the slow loading mentioned above, so I'm including it in the same report.

**Comment by Adamantcheese** [comment] 2019-08-09 03:50
This is related to #56 and #150. I'm half thinking that it's Cloudflare doing something strange but I don't know how to replicate it either, or even how to begin to figure out where the issue stems from.

**Comment by powerLien** [comment] 2019-08-10 03:38
Been messing around with the app, noticed two things:
1) It seems like killing the app via the crash app button in the dev options fixes both catalog and thread loading for a short time.
2) The thumbnail bug only seems to happen after swiping some arbitrary number of images away from the initial image you enter image viewing mode. I tried a process in a few threads where I expanded an image, swiped forward a few, exited image viewing mode, then expanded the image I ended on and swiped back to the original before exiting again, iterating by increasing how many images I swiped forwards and backwards until I got the thumbnail I was unable to exit from. This usually happened around 4-6 images away from the initial image.

**Comment by powerLien** [comment] 2019-08-12 05:25
I think I found the problem. I had some boards from 8chan still sitting in my board selection menu as well as in my bookmarks. When I deleted 8chan from Kuroba, it returned to a normal speed.

**Comment by Adamantcheese** [comment] 2019-08-12 05:37
Ah, then this may be a holdover from #47. While it doesn't save all of the boards now due to a workaround (the boards.json parsing code still exists, just isn't used), it used to, so you may have a spare ~18K boards sitting around as a result. I appreciate the update, but I'll leave this open just in case it is something else.

If anyone else has this problem, please double check in your Developer Settings how many Board rows you have; if it's over 5K and you have 8chan as a site, try removing it and please let me know if the problem is resolved.

**Comment by ghost** [comment] 2019-08-28 14:28
I'm getting this issue despite clearing the database completely. The loading icon freezes and I can't browse any board.

**Comment by Adamantcheese** [comment] 2019-08-29 00:01
This issue is seperate @ajtpak. See #342.

**Comment by Adamantcheese** [comment] 2019-10-03 00:27
Closed as 8chan is no longer a valid site in the application.

**Closed as completed by Adamantcheese** 2019-10-03 00:27 UTC
Labels: bug, cantrepro
