### ISSUE TITLE
No longer finding option to reply to a post via the post option menu

### ISSUE THREAD

**Issue by Toblerone1** [Adamantcheese/Kuroba#1053] opened 2020-08-11 01:51 UTC
Previous versions had a reply to post as well as reply quoting post in the post option menu. As well as an option to disable reply via clicking post number. Very much preferred replying to be via drop down menu. Accidentally opening replies via clicking post number is also frustrating and there used to be an option to disable it.

Not sure why it was changed to be this way, or if the update just turned something off I can't find in the settings after checking everything I could twice over

**Comment by Adamantcheese** [comment] 2020-08-11 02:01
Duplicate of #1023; already reverted on dev.

**Closed as completed by Adamantcheese** 2020-08-11 02:01 UTC
Labels: duplicate
