### ISSUE TITLE
Report "There's a New Post indicator that's stuck at the bottom"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1337] opened 2021-08-06 14:49 UTC
UUID: 4f43fee06388a486a629cd48872cd9be
Build flavor: dev
Version name: v4.13.6-3e9528b
OS info: Android 11, sdk version: 30
Report description: Problem is as described. For some reason the New Post indicator in a thread can sometimes get stuck.

**Comment by Adamantcheese** [comment] 2021-08-06 23:30
Duplicate of #1299.

**Closed as completed by Adamantcheese** 2021-08-06 23:30 UTC
Labels: duplicate
