### ISSUE TITLE
Can't show image

### ISSUE THREAD

**Issue by DeadNumbers** [Adamantcheese/Kuroba#846] opened 2020-04-02 19:36 UTC
v4.12.0

![изображение](https://user-images.githubusercontent.com/9416005/78294061-5ac69600-7532-11ea-891b-1b502ed6a106.png)

**Comment by Adamantcheese** [comment] 2020-04-03 01:21
Duplicate of #839, which has already been resolved.

**Closed as completed by Adamantcheese** 2020-04-03 01:21 UTC
Labels: duplicate
