### ISSUE TITLE
Strange glitch on some posts with attached images (latest dev)

### ISSUE THREAD

**Issue by exegg** [Adamantcheese/Kuroba#1236] opened 2021-01-26 15:04 UTC
Some posts glitch out when they have an attached pic. You can even get this error when trying to change the app theme.
It occurs randomly when you are browsing threads, specifically in post replies. In the example attached this one could be fixed temporarily by scrolling it out of sight, but when there's not enough posts to scroll you can't do this.

https://user-images.githubusercontent.com/19347211/105862377-18d97580-5fc6-11eb-8b7a-be5d007d014f.mp4

**Comment by Adamantcheese** [comment] 2021-01-27 02:20
Duplicate of #1214.

**Closed as completed by Adamantcheese** 2021-01-27 02:20 UTC
Labels: duplicate
