### ISSUE TITLE
Thread scrolling to top when updating

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#347] opened 2019-09-01 16:51 UTC
It's random tho
![ScreenRecord-2019-09-01-13-12-02](https://user-images.githubusercontent.com/29208110/64079590-8e50f180-ccbf-11e9-82ed-9871ca76a4d5.gif)

**Comment by K1rakishou** [comment] 2019-09-02 15:30
Duplicate of https://github.com/Adamantcheese/Kuroba/issues/229

**Closed as completed by K1rakishou** 2019-09-02 15:30 UTC
