### ISSUE TITLE
Reeport "Top layout breaks sometimes"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1227] opened 2021-01-07 21:04 UTC
UUID: d0f5239da4d090bab064af2fe4c6a04a
Build flavor: dev
Version name: v4.13.6-b4c45ba
OS info: Android 10, sdk version: 29
Report description: I think it usually happens on reload (when killed by LMK), not 100% sure.
https://streamable.com/q9pe7b

**Comment by Adamantcheese** [comment] 2021-01-08 02:36
Duplicate of #1082.

**Closed as completed by Adamantcheese** 2021-01-08 02:36 UTC
Labels: duplicate
