### ISSUE TITLE
Report "Crash on turn off and on screen"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#987] opened 2020-07-10 08:07 UTC
UUID: c64654475138d94a5e79f21e118eddc1
Build flavor: stable
Version name: v4.13.4
OS info: Android 9, sdk version: 28
Report description: The screen turn off, turning on again makes the app unrespond

**Comment by Adamantcheese** [comment] 2020-07-10 08:58
Duplicate of #913? I honestly don't have any information to go off of here.

**Comment by lewri** [comment] 2020-07-16 23:59
I can't replicate the behaviour here, or the behaviour of the one marked as a duplicate.

The only thing I can think of is the phone itself tries to kill the process to free memory, perhaps a bit too trigger happy about it. That probably isn't a problem with kuroba though. 

I get this behaviour happen sometimes with a big app like a game. But without any proper logs it's hard to say for sure.

**Comment by Adamantcheese** [comment] 2020-07-17 01:42
This might be a weird issue I have sometimes when I stop using Android Auto in my car and unlock it quickly afterwards, but it isn't Kuroba specifically that stalls and rather the entire OS. Locking and unlocking the screen fixes it in that case. Not really anything I can do from my perspective.

**Closed as completed by Adamantcheese** 2020-07-17 01:42 UTC
Labels: duplicate, cantrepro, report/crash report
