### ISSUE TITLE
[Feature Request] Option to not open reply input on clicking header of a post

### ISSUE THREAD

**Issue by Akul5b** [Adamantcheese/Kuroba#1084] opened 2020-08-31 09:58 UTC
Clicking a header of a post on a thread opens up the reply input and adds a link to that post to it. I find myself frequently accidentally clicking this while scrolling through the thread. Closing the reply input requires clicking the top left arrow, which is quite far from my hand position. Could an option be added to disable the opening of the reply input, if not that whole interaction area of a post.

**Comment by Adamantcheese** [comment] 2020-09-01 01:28
Duplicate of #1023. Also you can just press the back button on your device to close it instead of using the top left arrow.

**Closed as completed by Adamantcheese** 2020-09-01 01:28 UTC
