### ISSUE TITLE
Attempting to load new posts gives an "x new posts" popup

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1380] opened 2021-12-06 10:40 UTC
In the thread I was just reading I reached the bottom and checked for new posts just for a popup to appear. Clicking it bumps me up and reveals that the posts are not properly being marked as read.
The popup also shows if I tab out of the app and go back to it.
![Screenshot_20211206-033825.jpg](https://user-images.githubusercontent.com/30278765/144832020-d1929872-f27d-4982-ae5e-cfa9e10fe3b2.jpg)
Tested on v4.13.6-34a61da1 on a Samsung Note 10 Plus

**Comment by ghost** [comment] 2021-12-06 10:41
Also when new posts do happen the popup doesn't stop appearing. In this case it just says "12 new posts" instead of 11
![Screenshot_20211206-034122.jpg](https://user-images.githubusercontent.com/30278765/144832186-ed155993-9dcf-4a20-a3f0-c134a53d16bb.jpg)

**Comment by Adamantcheese** [comment] 2021-12-07 02:57
Duplicate of #1299.

**Closed as completed by Adamantcheese** 2021-12-07 02:57 UTC
Labels: duplicate
