### ISSUE TITLE
Report "[Bug] Regular links blend in with the foreground in the catalog."

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#879] opened 2020-05-07 21:28 UTC
UUID: 852935b0b1555ad1a5a81fa49704a7b2
Build flavor: dev
Version name: v4.12.0-c946806
OS info: Android 10, sdk version: 29
Report description: The link colors and the foreground colors for both light and dark themes are the same.

**Comment by Adamantcheese** [comment] 2020-05-08 03:36
Uh, what? I would honestly like to see a screenshot or something for this because that makes no sense. Everything's displaying just fine, emulator or hardware.
![image](https://user-images.githubusercontent.com/9031585/81367518-56961700-90a2-11ea-839f-ca0d4c7d6817.png)

**Comment by K1rakishou** [comment] 2020-05-08 06:03
Probably something device specific.

**Comment by Adamantcheese** [comment] 2020-05-08 06:06
It's using the regular old `android:textColorLink` attribute now that's used in TextViews as well, what stupid device is messing with that attribute and making it transparent

**Comment by K1rakishou** [comment] 2020-05-08 07:34
Well, usually samsung phones have a shit ton of problems with colors and stuff.

**Comment by ghost** [comment] 2020-05-08 17:00
This was my report, which was a duplicate of #876 and has already been fixed. By the way, my device is a Pixel 3 for reference.

**Comment by Adamantcheese** [comment] 2020-05-08 20:25
Duplicate of #876, per comment above.

**Closed as completed by Adamantcheese** 2020-05-08 20:25 UTC
Labels: duplicate, report/crash report
