### ISSUE TITLE
Report "Blurry pics"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1184] opened 2020-12-08 07:19 UTC
UUID: 355c55129988a2df7d6bcc154cbeb39b
Build flavor: dev
Version name: v4.13.6-6ddbf11
OS info: Android 10, sdk version: 29
Report description: It happens sometimes and don't go away. You tap on the thumbnail, a blurry version of the pic appears for a split second, then the full res pic appears then it turns blurry. Doesn't happen in stable

**Comment by Adamantcheese** [comment] 2020-12-08 07:44
Probably a dupe of #1071. I'll leave this open just in case.

**Comment by Adamantcheese** [comment] 2021-05-17 04:43
Closed with #1071's closure.

**Closed as completed by Adamantcheese** 2021-05-17 04:43 UTC
Labels: duplicate
