### ISSUE TITLE
New reCAPTCHA

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1364] opened 2021-09-25 13:39 UTC
Why have the devs not done anything to support the new reCAPTCHA? It was released ~3 months ago and nothing has been done by the devs

**Comment by ghost** [comment] 2021-09-26 22:24
Stable releases lag behind, you need the dev branch

**Comment by Adamantcheese** [comment] 2021-09-27 05:29
Duplicate of #1296. Captcha does work, but has not been pushed to release. Dev is working however.

**Comment by Adamantcheese** [comment] 2021-09-27 05:29
Also I'm the only developer here.

**Closed as completed by Adamantcheese** 2021-09-27 05:29 UTC
Labels: duplicate
