### ISSUE TITLE
[Feature Request] Option to show all (You) in the thread

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#31] opened 2019-06-04 19:52 UTC
Currently you can only see all your (You) in the thread by either scrolling and looking for highlighted posts or by searching for "(You)". This option would solve this. It could be placed under the three dots menu.

**Comment by Adamantcheese** [comment] 2019-06-05 03:27
Duplicate of #24.

**Closed as completed by Adamantcheese** 2019-06-05 03:27 UTC
Labels: duplicate
