### ISSUE TITLE
Images can fail to load when finished downloading

### ISSUE THREAD

**Issue by lewri** [Adamantcheese/Kuroba#1071] opened 2020-08-21 22:56 UTC
I've noticed this now in Android 10 on current stable build. Never in 9.

Sometimes when you view an image that's quite big in size it gets stuck in thumbnail quality and hangs at the end of loading the image.

It resolves by coming out of the image viewer and going back in. But if you swipe to another image and back it still gets stuck in thumbnail quality.

**Comment by Adamantcheese** [comment] 2020-08-21 23:14
Yeah I've noticed this one as well. I've caught it once that the error being thrown is a SocketTimeoutException, so I'm not sure as of right now what the fix might be.

**Comment by lewri** [comment] 2020-08-22 08:07
From a little playing about it seems to be caused by the concurrent chunked image downloading feature.
If I turn it off (set to 1 chunk) it seems to go away.

**Comment by K1rakishou** [comment] 2020-08-23 20:56
I noticed it too today. When you are downloading an image chunked, one of the chunks just randomly gets stuck at like 80-90% without any errors. ~Setting the chunks count to 1 resolves the issue.~ No, this happens with only 1 chunk  downloads too. I initially though that it's because of the http/2 but disabling it didn't change anything. I think it's something server-side related. Oh, the new okhttp version might be the issue too. I didn't try rolling it back. And yeah, trying this thing with other sites should help figure out the problem too. But it's most likely the server issue or, maybe, we have been "noticed", since we are probably the only client that uses "Partial-Content", and they didn't like that we are using it (but then they could have just disabled it).

**Comment by K1rakishou** [comment] 2020-09-01 20:30
So after more testing I can say that's it's the 4chan's server doing some shady shit. I noticed that once the download gets stuck, if you wait for like 5-10 seconds then in the end it successfully competes. I have no idea why is the server doing this shit.

**Comment by Adamantcheese** [comment] 2020-09-02 01:59
Is it Cloudflare or 4chan's servers though, that's the question. I don't know what sort of configuration options Cloudflare DDOS protection provides that might be messing with it as well. At the very least setting it to 1 chunk mitigates the problem _enough_ that it's not a huge deal.

**Comment by K1rakishou** [comment] 2020-09-02 06:49
It's most likely 4chan servers, I haven't noticed it happening when viewing catalog images (which are almost always cached by cloudflare) but it does happen in old threads where there are few posters. Also, I don't understand why it still happens even with 1 chunk per download because I don't use the "Range: x-y" header when this thing is disabled so if the problem is in Partial-Content then it should work.

**Comment by K1rakishou** [comment] 2020-09-02 11:10
Alright, I sent a bug report to 4chan devs (or to whoever reads their feedback) so let's hope it helps.

**Comment by K1rakishou** [comment] 2020-09-05 08:28
I think I figured something out. 

```
2020-09-05 11:14:13.117 I/okhttp.OkHttpClient: --> GET https://i.4cdn.org/c/1598499471810.jpg
2020-09-05 11:14:13.117 I/okhttp.OkHttpClient: --> END GET
2020-09-05 11:14:13.120 I/okhttp.OkHttpClient: --> GET https://i.4cdn.org/c/1598499471810.jpg
2020-09-05 11:14:13.120 I/okhttp.OkHttpClient: --> END GET
2020-09-05 11:14:15.329 I/okhttp.OkHttpClient: <-- 206 https://i.4cdn.org/c/1598499471810.jpg (2211ms)
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: cf-cache-status: MISS
2020-09-05 11:14:18.125 I/okhttp.OkHttpClient: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
2020-09-05 11:14:18.126 D/KurobaEx-dev | ChunkDownloader: [OkHttp https://i.4cdn.org/...]: Couldn't get chunk response, reason = SocketTimeoutException (timeout) (https://i.4cdn.org/c/1598499471810.jpg) 556966..1113931, time = 5009ms
2020-09-05 11:14:18.133 I/okhttp.OkHttpClient: --> GET https://i.4cdn.org/c/1598499471810.jpg
2020-09-05 11:14:18.134 I/okhttp.OkHttpClient: --> END GET
2020-09-05 11:14:19.280 I/okhttp.OkHttpClient: <-- END HTTP (binary 556966-byte body omitted)
2020-09-05 11:14:19.283 D/KurobaEx-dev | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(0) (https://i.4cdn.org/c/1598499471810.jpg) called for chunk 0..556965
2020-09-05 11:14:19.297 I/okhttp.OkHttpClient: <-- 206 https://i.4cdn.org/c/1598499471810.jpg (1161ms)
2020-09-05 11:14:19.298 I/okhttp.OkHttpClient: cf-cache-status: HIT
2020-09-05 11:14:19.335 D/KurobaEx-dev | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(0) success, url = https://i.4cdn.org/c/1598499471810.jpg, chunk 0..556965
2020-09-05 11:14:20.890 I/okhttp.OkHttpClient: <-- END HTTP (binary 556966-byte body omitted)
2020-09-05 11:14:20.894 D/KurobaEx-dev | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(1) (https://i.4cdn.org/c/1598499471810.jpg) called for chunk 556966..1113931
2020-09-05 11:14:20.943 D/KurobaEx-dev | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(1) success, url = https://i.4cdn.org/c/1598499471810.jpg, chunk 556966..1113931
```

Here is a log of opening an image that is not cached by the cloudflare, with 2 chunks per download, and 5 seconds for all OkHttp timeouts (read/write/connect, call timeout is set to default). HTTP/2 is enabled, ipv6 is disabled.

So what's going on here. First, we send two GET requests (one per chunk)
```
2020-09-05 11:14:13.117 I/okhttp.OkHttpClient: --> GET https://i.4cdn.org/c/1598499471810.jpg
2020-09-05 11:14:13.117 I/okhttp.OkHttpClient: --> END GET
2020-09-05 11:14:13.120 I/okhttp.OkHttpClient: --> GET https://i.4cdn.org/c/1598499471810.jpg
2020-09-05 11:14:13.120 I/okhttp.OkHttpClient: --> END GET
```

Server returns us response with header "cf-cache-status: MISS" meaning that the image was served directly from the 4chan server.

```
2020-09-05 11:14:15.329 I/okhttp.OkHttpClient: <-- 206 https://i.4cdn.org/c/1598499471810.jpg (2211ms)
2020-09-05 11:14:15.329 I/okhttp.OkHttpClient: date: Sat, 05 Sep 2020 08:14:15 GMT
2020-09-05 11:14:15.329 I/okhttp.OkHttpClient: content-type: image/jpeg
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: content-length: 556966
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: last-modified: Thu, 27 Aug 2020 03:37:52 GMT
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: etag: "5f472a90-10ff4c"
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: cf-cache-status: MISS
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: expires: Tue, 06 Oct 2020 08:14:14 GMT
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: cache-control: public, max-age=2678400
2020-09-05 11:14:15.330 I/okhttp.OkHttpClient: content-range: bytes 0-556965/1113932
2020-09-05 11:14:15.331 I/okhttp.OkHttpClient: cf-request-id: 04feed988a00007b1b3c234200000001
2020-09-05 11:14:15.331 I/okhttp.OkHttpClient: expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
2020-09-05 11:14:15.331 I/okhttp.OkHttpClient: server: cloudflare
2020-09-05 11:14:15.331 I/okhttp.OkHttpClient: cf-ray: 5cde7ed41b437b1b-DME
```

Note that there is no 
```
<-- END HTTP (binary 556966-byte body omitted)
```
Which I'm not sure what that even means - no body? Or the body is not ready?

So we are trying to read the body, but we fail (because the timeout is only 5 seconds, not 30 like it is right now in kuroba. If you leave it at 30 seconds then we will be waiting the whole fucking 30 seconds). This is probably the main problem - there is no body for us to read so we do nothing until we fail with timeout.

```
2020-09-05 11:14:18.125 I/okhttp.OkHttpClient: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
2020-09-05 11:14:18.126 D/KurobaEx-dev | ChunkDownloader: [OkHttp https://i.4cdn.org/...]: Couldn't get chunk response, reason = SocketTimeoutException (timeout) (https://i.4cdn.org/c/1598499471810.jpg) 556966..1113931, time = 5009ms
```

Then we are trying to download it again (because there is the retry-on-IO-error mechanism which has 5 attempts).

```
2020-09-05 11:14:19.297 I/okhttp.OkHttpClient: date: Sat, 05 Sep 2020 08:14:19 GMT
2020-09-05 11:14:19.297 I/okhttp.OkHttpClient: content-type: image/jpeg
2020-09-05 11:14:19.297 I/okhttp.OkHttpClient: content-length: 556966
2020-09-05 11:14:19.297 I/okhttp.OkHttpClient: last-modified: Thu, 27 Aug 2020 03:37:52 GMT
2020-09-05 11:14:19.298 I/okhttp.OkHttpClient: etag: "5f472a90-10ff4c"
2020-09-05 11:14:19.298 I/okhttp.OkHttpClient: cf-cache-status: HIT
2020-09-05 11:14:19.298 I/okhttp.OkHttpClient: age: 4
2020-09-05 11:14:19.298 I/okhttp.OkHttpClient: expires: Tue, 06 Oct 2020 08:14:18 GMT
2020-09-05 11:14:19.298 I/okhttp.OkHttpClient: cache-control: public, max-age=2678400
2020-09-05 11:14:19.299 I/okhttp.OkHttpClient: content-range: bytes 556966-1113931/1113932
2020-09-05 11:14:19.300 I/okhttp.OkHttpClient: cf-request-id: 04feedac2900007b1b3c318200000001
2020-09-05 11:14:19.300 I/okhttp.OkHttpClient: expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
2020-09-05 11:14:19.300 I/okhttp.OkHttpClient: server: cloudflare
2020-09-05 11:14:19.300 I/okhttp.OkHttpClient: cf-ray: 5cde7ef378477b1b-DME
2020-09-05 11:14:20.890 I/okhttp.OkHttpClient: <-- END HTTP (binary 556966-byte body omitted)
```

This time we get the response with "cf-cache-status: HIT" meaning it was served from the Cloudflare servers, and this time it actually has the body - "<-- END HTTP (binary 556966-byte body omitted)". And we successfully read it!

```
2020-09-05 11:14:19.283 D/KurobaEx-dev | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(0) (https://i.4cdn.org/c/1598499471810.jpg) called for chunk 0..556965
2020-09-05 11:14:19.335 D/KurobaEx-dev | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(0) success, url = https://i.4cdn.org/c/1598499471810.jpg, chunk 0..556965
```

**Comment by K1rakishou** [comment] 2020-09-05 08:30
So one solution which "helps" is to lower timeouts for DOWNLOADER_OKHTTP_CLIENT_NAME.

```
OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder()
                .connectTimeout(5, SECONDS)
                .readTimeout(5, SECONDS)
                .writeTimeout(5, SECONDS)
                .protocols(okHttpProtocols.protocols)
                .dns(okHttpDns);
```

We will wait only 5 seconds instead of 30 before retrying to download the image. I still have no idea what to do with the response having no actual image in it's body though.

**Comment by K1rakishou** [comment] 2020-09-05 08:36
Maybe the timeouts can be tuned better than that (higher connect timeout, lower read timeout ~and we don't even need the write timeout so leave it with default value~ no, apparently write timeout should be lowered too)?

**Comment by K1rakishou** [comment] 2020-09-05 09:26
After some testing I think 

```
.readTimeout(5, SECONDS)
.writeTimeout(5, SECONDS)
```

is good enough.

**Comment by Adamantcheese** [comment] 2020-09-19 05:41
[From the source of the intercepting logger](https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt#L223), ```<-- END HTTP (binary 556966-byte body omitted)``` isn't displayed because the SocketTimeoutException is thrown before that code is ever gotten to. Something in the chain is taking a longer time to process than it should, [not that there's no body in the response, which would trigger this code](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/http/RealInterceptorChain.kt#L118). I guess knowing if you've installed the interceptor as an application one or a network one may be of some help. [Perhaps something could be done in a application interceptor](https://square.github.io/okhttp/interceptors/#choosing-between-application-and-network-interceptors), like changing the timeout dynamically if Cloudflare reports a cache-miss. I can definitely change the timeouts for the entire client or even use newBuilder() and set the timeouts per request, but that just seems too much like a crude hack of a fix for this strange issue.

**Comment by Adamantcheese** [comment] 2020-09-19 05:52
I should also point out that Cloudflare is always the one that is actually providing the response if it's enabled for a server, even if the resource is requested from the origin server; see Response phase in https://support.cloudflare.com/hc/en-us/articles/115003206852-Understanding-Origin-Cache-Control#h_203520451761546894832148. So it can't be 4chan's servers on this one, maybe Cloudflare's servers are doing something new and strange when a cache miss occurs.

**Comment by K1rakishou** [comment] 2020-09-19 07:44
>I guess knowing if you've installed the interceptor as an application one or a network one may be of some help.

Damn I didn't even notice there were two kinds of interceptors and I don't remember how exactly I installed the LoggingInterceptor.

>but that just seems too much like a crude hack of a fix for this strange issue.

Yeah I know it's a shitty hack, but at least you don't have to wait for 30 seconds until the image is downloaded. It's a temporary solution.

>like changing the timeout dynamically if Cloudflare reports a cache-miss.

This is probably the best solution until the actual reason is found

**Comment by Adamantcheese** [comment] 2020-12-14 02:56
I've added in some debug stuff and it looks like Cloudflare/4Chan are returning an incorrect amount of bytes for things that have a cache miss? Most of the data is there, but for some reason it's missing some amount of bytes? Here's a cleaned up log output:
```
D/Kuroba-dev | ChunkPersister: {0},   {8192}, {119404} --chunk, progress, total for chunk
D/Kuroba-dev | ChunkPersister: {0},  {16384}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {24576}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {32768}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {40960}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {49152}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {57344}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {65536}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {73728}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {81920}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {90112}, {119404}
D/Kuroba-dev | ChunkPersister: {0},  {98304}, {119404}
D/Kuroba-dev | ChunkPersister: {0}, {106496}, {119404}
D/Kuroba-dev | ChunkPersister: {0}, {114688}, {119404}
D/Kuroba-dev | ChunkPersister: {0}, {119404}, {119404} --success!

D/Kuroba-dev | ChunkPersister: {1},   {8192}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {16384}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {24576}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {32768}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {40960}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {49152}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {57344}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {65536}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {73728}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {81920}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {90112}, {119405}
D/Kuroba-dev | ChunkPersister: {1},  {98304}, {119405}
D/Kuroba-dev | ChunkPersister: {1}, {106496}, {119405}
D/Kuroba-dev | ChunkPersister: {1}, {113320}, {119405} --should be 114,668; only read 6,824 bytes
                                                       --expected {1}, {119405}; missing 6085 bytes in total response
E/Kuroba-dev | ConcurrentChunkedFileDownloader: Error while trying to download, class = SocketTimeoutException, message = timeout
E/Kuroba-dev | FileCacheV2: Unknown exception, class = SocketTimeoutException, message = timeout
```
Because the buffered source from the body is reporting what the HTTP header says the length is, when reading from the source it gets stuck waiting, expecting those extra bytes to be there, at which point it times out and throws the exception.

Note that I also tried disabling HTTP/2, thinking that it might be a BufferedSource implementation issue. Unfortunately, it has the same issue. The two protocols do end up having different BufferedSource implementations (FramingSource vs FixedLengthSource), but it doesn't have any effect on what occurs.

Of note: this always occurs on the last chunk for some reason, whether it's 1, 2, 4, or whatever amount of chunks. Always with a cache-miss though on the first chunk, but cache hits on all chunks after.

**Comment by Adamantcheese** [comment] 2020-12-14 07:40
Other stuff of note, it seems that yes, images that have that weird cache-miss-first, cache-hit-second chunk thing going on DO complete, after 100 seconds plus a few hundred milliseconds of waiting. I'm certain that has to be a Cloudflare thing.

**Comment by K1rakishou** [comment] 2020-12-14 09:15
I wonder if it's easier to just completely disable it for 4chan.

**Comment by Adamantcheese** [comment] 2021-05-17 04:42
Concurrent chunked downloading has been removed as part of a cache rework, so this issue is resolved. See 033010ade32c316209ab9e710b21b8e10d9295d9.

**Closed as completed by Adamantcheese** 2021-05-17 04:42 UTC
Labels: bug
