### ISSUE TITLE
Crash report "java.lang.UnsupportedOperationException 	at com.github.adamantcheese.chan.ui.controller.AlbumViewController.getPostForPostImage(AlbumViewController.java:151)"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1373] opened 2021-10-15 09:35 UTC
Crash report
UUID: 0fa265c9505582fcbb6176ccc177bca2
Build flavor: dev
Version name: v4.13.6-34a61da1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(October 15, 2021 7:39:31 AM UTC) ===
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.UnsupportedOperationException
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.AlbumViewController.getPostForPostImage(AlbumViewController.java:151)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.appendAdditionalSubDirectories(ImageViewerController.java:313)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveShare(ImageViewerController.java:281)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveClicked(ImageViewerController.java:228)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.lambda$Gz-89eDToQVexSOaWvGSnEF0dtc(Unknown Source:0)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ImageViewerController$Gz-89eDToQVexSOaWvGSnEF0dtc.onClick(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuItem.performClick(ToolbarMenuItem.java:209)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.-$$Lambda$XkVMUVrFUsNlqIK8NbX-1gYdRjU.onClick(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.performClick(View.java:7862)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.performClickInternal(View.java:7831)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.access$3600(View.java:879)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:29359)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:237)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 29
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-34a61da1
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-G960U


=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.UnsupportedOperationException
	at com.github.adamantcheese.chan.ui.controller.AlbumViewController.getPostForPostImage(AlbumViewController.java:151)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.appendAdditionalSubDirectories(ImageViewerController.java:313)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveShare(ImageViewerController.java:281)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveClicked(ImageViewerController.java:228)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.lambda$Gz-89eDToQVexSOaWvGSnEF0dtc(Unknown Source:0)
	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ImageViewerController$Gz-89eDToQVexSOaWvGSnEF0dtc.onClick(Unknown Source:2)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuItem.performClick(ToolbarMenuItem.java:209)
	at com.github.adamantcheese.chan.ui.toolbar.-$$Lambda$XkVMUVrFUsNlqIK8NbX-1gYdRjU.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: content://com.android.externalstorage.documents/tree/0123-4567%3A.Pictures%2FKuroba, active: SAF
Phone layout mode: AUTO
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by Adamantcheese** [comment] 2021-10-15 21:02
Duplicate of #1349.

**Closed as completed** 2021-10-15 21:02 UTC
Labels: duplicate
