### ISSUE TITLE
Gifs not working

### ISSUE THREAD

**Issue by nikgtasa** [Adamantcheese/Kuroba#58] opened 2019-06-09 08:22 UTC
Can't load gifs, latest build, vpn doesn't matter, happens on any board.

[SCR_20190609_111600.mp4.zip](https://github.com/Adamantcheese/Kuroba/files/3269354/SCR_20190609_111600.mp4.zip)

**Comment by Adamantcheese** [comment] 2019-06-09 09:47
If you could provide some logs, that would be very nice. You can tap the build number to enable dev settings, go to the bottom and open them up, then open up the logs. You can copy those from the upper right menu and paste them here or in a pastebin.

**Comment by nikgtasa** [comment] 2019-06-09 10:13
--------- beginning of system
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/androidtc: Loading ModelFile { path=/data/misc/textclassifier/textclassifier.model name=textclassifier.model version=608 locales=en }
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/androidtc: Loading ModelFile { path=/data/misc/textclassifier/textclassifier.model name=textclassifier.model version=608 locales=en }
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
D/TextClassifierService: No configured system TextClassifierService
--------- beginning of main
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /c/ has already been requested
W/Kuroba | PageRequestManager: Board /c/ has already been requested
W/Kuroba | PageRequestManager: Board /animu/ has already been requested
W/Kuroba | PageRequestManager: Board /hikki/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /animu/ has already been requested
W/Kuroba | PageRequestManager: Board /hikki/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
I/mantcheese.cha: Background concurrent copying GC freed 62987(4MB) AllocSpace objects, 4(132KB) LOS objects, 50% free, 15MB/30MB, paused 1.470ms total 186.851ms
I/mantcheese.cha: Background concurrent copying GC freed 126617(11MB) AllocSpace objects, 34(3MB) LOS objects, 49% free, 23MB/46MB, paused 478us total 200.689ms
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: c.a.a.u
I/Kuroba | ChanThreadLoader: 	at c.a.a.a.a.a(Unknown Source:266)
I/Kuroba | ChanThreadLoader: 	at c.a.a.i.run(Unknown Source:35)
E/Kuroba | FileCacheDownloader: [https://i.4cdn.org/wsg/1558215044574.gif] exception
E/Kuroba | FileCacheDownloader: java.net.SocketTimeoutException: timeout
E/Kuroba | FileCacheDownloader: 	at g.q.b(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at g.c.a(Unknown Source:7)
E/Kuroba | FileCacheDownloader: 	at g.b.a(Unknown Source:23)
E/Kuroba | FileCacheDownloader: 	at g.v.a(Unknown Source:46)
E/Kuroba | FileCacheDownloader: 	at g.v.b(Unknown Source:27)
E/Kuroba | FileCacheDownloader: 	at f.a.d.b.g(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.a.d.b.a(Unknown Source:34)
E/Kuroba | FileCacheDownloader: 	at f.a.b.d.a(Unknown Source:2)
E/Kuroba | FileCacheDownloader: 	at f.a.c.b.a(Unknown Source:160)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.b.b.a(Unknown Source:27)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.a.a.b.a(Unknown Source:132)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.a.c.a.a(Unknown Source:161)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.k.a(Unknown Source:23)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.I.a(Unknown Source:120)
E/Kuroba | FileCacheDownloader: 	at f.I.execute(Unknown Source:28)
E/Kuroba | FileCacheDownloader: 	at com.github.adamantcheese.chan.b.a.o.g(Unknown Source:49)
E/Kuroba | FileCacheDownloader: 	at com.github.adamantcheese.chan.b.a.o.f(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at com.github.adamantcheese.chan.b.a.o.run(Unknown Source:11)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | FileCacheDownloader: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | FileCacheDownloader: Caused by: java.net.SocketException: socket is closed
E/Kuroba | FileCacheDownloader: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:551)
E/Kuroba | FileCacheDownloader: 	at g.p.a(Unknown Source:35)
E/Kuroba | FileCacheDownloader: 	at g.b.a(Unknown Source:7)
E/Kuroba | FileCacheDownloader: 	... 28 more
I/ViewRootImpl: CPU Rendering VSync enable = false
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /animu/ has already been requested
W/Kuroba | PageRequestManager: Board /hikki/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /animu/ has already been requested
W/Kuroba | PageRequestManager: Board /hikki/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
E/Kuroba | FileCacheDownloader: [https://i.4cdn.org/wsg/1558215273708.gif] exception
E/Kuroba | FileCacheDownloader: java.net.SocketTimeoutException: timeout
E/Kuroba | FileCacheDownloader: 	at g.q.b(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at g.c.a(Unknown Source:7)
E/Kuroba | FileCacheDownloader: 	at g.b.a(Unknown Source:23)
E/Kuroba | FileCacheDownloader: 	at g.v.a(Unknown Source:46)
E/Kuroba | FileCacheDownloader: 	at g.v.b(Unknown Source:27)
E/Kuroba | FileCacheDownloader: 	at f.a.d.b.g(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.a.d.b.a(Unknown Source:34)
E/Kuroba | FileCacheDownloader: 	at f.a.b.d.a(Unknown Source:2)
E/Kuroba | FileCacheDownloader: 	at f.a.c.b.a(Unknown Source:160)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.b.b.a(Unknown Source:27)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.a.a.b.a(Unknown Source:132)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.a.c.a.a(Unknown Source:161)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.k.a(Unknown Source:23)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:153)
E/Kuroba | FileCacheDownloader: 	at f.a.c.h.a(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at f.I.a(Unknown Source:120)
E/Kuroba | FileCacheDownloader: 	at f.I.execute(Unknown Source:28)
E/Kuroba | FileCacheDownloader: 	at com.github.adamantcheese.chan.b.a.o.g(Unknown Source:49)
E/Kuroba | FileCacheDownloader: 	at com.github.adamantcheese.chan.b.a.o.f(Unknown Source:4)
E/Kuroba | FileCacheDownloader: 	at com.github.adamantcheese.chan.b.a.o.run(Unknown Source:11)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | FileCacheDownloader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | FileCacheDownloader: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | FileCacheDownloader: Caused by: java.net.SocketException: socket is closed
E/Kuroba | FileCacheDownloader: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:551)
E/Kuroba | FileCacheDownloader: 	at g.p.a(Unknown Source:35)
E/Kuroba | FileCacheDownloader: 	at g.b.a(Unknown Source:7)
E/Kuroba | FileCacheDownloader: 	... 28 more
I/ViewRootImpl: CPU Rendering VSync enable = false
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /hgg/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested
W/Kuroba | PageRequestManager: Board /animu/ has already been requested
W/Kuroba | PageRequestManager: Board /hikki/ has already been requested
W/Kuroba | PageRequestManager: Board /v/ has already been requested

**Comment by Adamantcheese** [comment] 2019-06-09 19:05
I appreciate the logs and I'll look into it. At the very least I'll change it so that a bunch of those messages don't appear in the log because they're pretty useless.

**Comment by Adamantcheese** [comment] 2019-06-10 01:29
Yeah I still can't reproduce your issue. All I know is that something is timing out, which may be a problem with your network doing something strange.

**Comment by nikgtasa** [comment] 2019-06-10 12:38
Well it does work in browser and omnichan. I reinstalled the app and the issue is still present.

**Comment by Adamantcheese** [comment] 2019-06-25 04:29
Please confirm the issue still occurs as of the most recent version.

**Comment by nikgtasa** [comment] 2019-06-25 09:52
It does unfortunately. I've used different vpn's, build is 4.3.2 but the issue didn't go away.
It's present on any chan.


I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.TimeoutError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:137)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)

**Comment by Adamantcheese** [comment] 2019-06-27 00:28
Since you've mentioned you're using a VPN and the only error here is a timeout, I have reason to believe that there is nothing wrong with the program and it's literally just taking more than 10 seconds to do anything because of the huge amount of delay added in. Closing as a result.

**Closed by Adamantcheese** 2019-06-27 00:28 UTC
Labels: bug, cantrepro

**Comment by nikgtasa** [comment] 2019-06-27 10:04
I've mentioned vpn because i mainly use 8chan but the problem is prevalent everywhere without it.
Other chan browsers don't have that but they're also not as good.
