### ISSUE TITLE
[IMPROVEMENT] When using the app with the phone layout it's kinda hard to click images sometimes

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#398] opened 2019-10-31 11:57 UTC
So it's hard because instead of opening the image, the whole fragment (with current thread ViewThreadController I guess?) is getting moved by the finger. Slide mode doesn't have this problem  probably because, I guess, there is a little threshold before it redirects the motion event to start moving the fragment. The same threshold should be applied in the phone mode.

**Comment by Adamantcheese** [comment] 2019-10-31 13:45
I'm pretty sure this is a dupe of #349?

**Comment by K1rakishou** [comment] 2019-10-31 19:30
No this one is different. You can notice the difference by switching between the phone layout and slide layout and by slightly moving your finger horizontally when viewing a thread. You will notice that it starts moving the fragment faster in phone layout because there is no minimum threshold for ignoring the move events.

**Closed as completed** 2019-11-06 02:26 UTC
Labels: enhancement
