### ISSUE TITLE
[Feature Request] Implement an option to hide status/navigation bar (full screen mode)

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#29] opened 2019-06-04 19:32 UTC

**Comment by Adamantcheese** [comment] 2019-06-25 03:59
Dupe of #22.

**Closed as completed by Adamantcheese** 2019-06-25 03:59 UTC
Labels: wontfix

**Comment by floppyD** [comment] 2019-06-25 04:08
It's not, my issue is about a feature to make the app stay in fullscreen all the time, with the status/navigation bar hidden. Just like apps such as games and media players do. Basically doing pic related but natively.
![Screenshot_20190625-010331](https://user-images.githubusercontent.com/29208110/60068572-b5021300-96e5-11e9-8d62-9a57c761d7bb.png)

**Comment by Adamantcheese** [comment] 2019-06-25 04:11
Ah, alright.

**Comment by floppyD** [comment] 2019-06-25 04:20
🤔
