### ISSUE TITLE
Long threads reset to original screen position after some scrolling

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1362] opened 2021-09-24 17:59 UTC
I found an issue where after tapping a reply notification and getting put in its thread I was unable to scroll up or down without being teleported to the post that I was at before scrolling (about the middle of the thread)
The top/bottom/new buttons refused to work until I closed the thread and went back to it after opening a new one (slide mode)

Tested on v4.13.6-34a61da1 on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment] 2023-07-31 05:35
Duplicate of #1201.

**Closed as completed by Adamantcheese** 2023-07-31 05:35 UTC
