### ISSUE TITLE
[Bug] Thread randomly scrolling/skipping to top

### ISSUE THREAD

**Issue by lplp6lkhp** [Adamantcheese/Kuroba#229] opened 2019-07-24 16:01 UTC
https://streamable.com/2imat
It only happens twice in this recording, it doesn't happen later.
I am on a Samsung Galaxy S10 (not S10e or S10+, just S10). Kuroba version 4.5.2-dev
Thought it might have to do with auto refresh but at the beginning it happened when there was 9 seconds left on the auto refresh. Happened a few times before I could record too. I'm not able to replicate this bug, so I'm unsure what leads to it, it just happens sometimes when I'm in a thread.
Thanks for all your work.

**Comment by Adamantcheese** [comment] 2019-07-25 00:15
That is strange indeed. I'm not entirely sure I'll be able to replicate it, but if it does come up during any testing I'll probe further.

**Comment by Adamantcheese** [comment] 2019-08-03 03:49
Well it happened to me, but I have no idea why. So I can at least confirm it.

**Comment by Adamantcheese** [comment] 2019-08-06 07:02
I have a method of reproduction now, but I don't know why it's happening, and it's only for Phone mode. If you go into a thread, go to the bottom (either via the button or scrolling), then open up a search, type something in, close out of it entirely, then go to the bottom again and hit the load button, you'll magically scroll to the top. It's like the last position is being saved for when the search is open, even though you can debug through it and definitely see that the bottom position is being saved. Given that this only started happening as a result of thread saving being added, I'm looking towards it as the culprit, again, unfortunately. The same thing may happen on other layout modes, but far less frequently. @K1rakishou, if you have any input that would be very useful.

**Comment by K1rakishou** [comment] 2019-08-06 07:15
Yeah, I'll try to look into it. For now I can say that I did touch the saving of the last viewed post into the DB but I did it in #247 which is not merged yet.

**Comment by K1rakishou** [comment] 2019-08-09 18:27
Well, after a several attempts I couldn't reproduce this issue myself. I tried threads with different amount of posts, archived threads, downloaded threads.

**Comment by Adamantcheese** [comment] 2019-08-09 22:10
Weird. I'll leave this open until I can confirm it's not happening anymore or find the reason why.

**Comment by lplp6lkhp** [comment] 2019-08-10 00:35
Adamantcheese's method of reproduction works for me. I do use phone layout and Kuroba is up to date: https://streamable.com/o61jr

**Comment by Adamantcheese** [comment] 2019-08-18 23:59
I have a new method of reproduction that's related, but not exactly the same.
1) Open up a board on Lainchan, say /λ/.
2) Open up a thread you've never been in.
3) Hit the 3 dot menu and tap "Bottom". Sometimes you can scroll to the bottom and tap it fast enough as well.
4) Tap the thread status cell.
You'll scroll to the top. If you scroll down in this state and repeat the steps, then you'll scroll back to whatever your last scroll position was.

**Comment by ownBard** [comment] 2019-11-10 22:48
I'm often getting this same behaviour when tapping the view new posts snackbar. Never really noticed it before though.

**Comment by K1rakishou** [comment] 2019-11-28 14:27
~~Alright, I've just managed to reproduce this thing using @Adamantcheese STR. Apparently it works on any thread you have never been in. You need to open it and quickly press BOTTOM button. Then it will start scrolling you to the top every time you click update thread post cell. Apparently this happens because it wrongly sets the lastViewPost id.~~

~~UPD: it happend to me once and doesn't happen anymore.~~

UPD2: I have the STR.
Similar to @Adamantcheese STR but before opening a thread you have never been in you need to **force stop the app**. I guess you can also clear the app data so you can open the same thread many times to debug this shit. So, basically:
- Clear app data (don't forget to export settings beforehand). OR force stop the app.
- Open any thread of /hr/ you have never been in (or just any thread on /hr/ after clearing the app data).
- Quickly click the BOTTOM button in the thread menu.
- Click the update thread post cell.

You should also print into the log the lastViewedPostNo (or whatever it's called) before doing this because this is a possible culprit.

**Comment by Adamantcheese** [comment] 2019-12-02 04:40
`lastViewed` is only used for the "new posts" indicator bar, or when you tap the "x new posts" snackbar to find the last viewed post so it can go to that post. I don't have any reason to suspect that variable. The values returned from `getIndexAndTop` are what set the scroll position and that's what you should be looking at.
In addition, letting the thread update itself once you're at the bottom of a thread will also trigger it when in that state (no user input required), so it's the layout manager laying everything out again and resetting the scroll position. I don't know why it's treating things like everything needs to be laid out again though, even when there are no new posts (which can be easily reproduced using a site that is slow, like Arisuchan).

**Comment by Adamantcheese** [comment] 2020-10-06 01:00
Additional info provided thanks to @K1rakishou, so this should be fixable now!
https://github.com/airbnb/epoxy/issues/224#issuecomment-305883735

**Closed as completed** 2020-10-08 02:17 UTC
Labels: bug
