### ISSUE TITLE
Report "Relatively obscure app crash when pressing buttons too quickly"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#891] opened 2020-05-17 08:35 UTC
UUID: 47281b42bc1da4b7620876733a0c10d2
Build flavor: stable
Version name: v4.12.0
OS info: Android 10, sdk version: 29
Report description: When viewing images in Gallery mode, if you tap the Jump to Post arrow, then quickly tap the Image Gallery button (which replaces the Jump to Post arrow, as the app is going back to post view mode), before the animation finishes, the app will hang. Hitting the Image Gallery butting again will subsequently crash the app.

This is not an intrusive crash, and is easily avoidable.
Logs:
```
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | AndroidUtils: view.getViewTreeObserver() is another viewtreeobserver! replacing with the new one
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to read from field 'com.github.adamantcheese.chan.ui.toolbar.NavigationItem com.github.adamantcheese.chan.controller.Controller.navigation' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.ui.NavigationControllerContainerLayout.onInterceptTouchEvent(NavigationControllerContainerLayout.java:149)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2609)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
E/Kuroba | UNCAUGHT: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:481)
E/Kuroba | UNCAUGHT: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1855)
E/Kuroba | UNCAUGHT: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3993)
E/Kuroba | UNCAUGHT: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
E/Kuroba | UNCAUGHT: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:439)
E/Kuroba | UNCAUGHT: 	at android.view.View.dispatchPointerEvent(View.java:13705)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5488)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5291)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4794)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4847)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4813)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4953)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4821)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5010)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4794)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4847)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4813)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4821)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4794)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7519)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7488)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7449)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7644)
E/Kuroba | UNCAUGHT: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
E/Kuroba | UNCAUGHT: 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/Kuroba | UNCAUGHT: 	at android.os.MessageQueue.next(MessageQueue.java:339)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:314)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7418)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 29
E/Kuroba | UNCAUGHT: App Version: v4.12.0
E/Kuroba | UNCAUGHT: Development Build: Release
E/Kuroba | UNCAUGHT: Phone Model: Sony H8314
I/Kuroba | WakeManager: Started background alarm with an interval of 5 minutes
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 10:01:52 AM
```

**Comment by K1rakishou** [comment] 2020-05-17 08:36
I remember some similar crash was fixed recently but maybe this is another way to reproduce it.

**Comment by Adamantcheese** [comment] 2020-05-17 08:40
Duplicate of #852.

**Closed as completed by Adamantcheese** 2020-05-17 08:40 UTC
Labels: duplicate, report/crash report
