### ISSUE TITLE
Failed to show image error on all boards

### ISSUE THREAD

**Issue by AstroShogun** [Adamantcheese/Kuroba#1426] opened 2023-05-26 23:32 UTC
As the image shows, I get presented with an error on trying to view images and GIFs. WebM videos work fine with no error.
![Screenshot_20230527_003106](https://github.com/Adamantcheese/Kuroba/assets/134747709/2d46a774-eacb-45ac-b79d-931ef4163d5b)

**Comment by Adamantcheese** [comment] 2023-05-27 16:01
Duplicate of #1425.

**Closed as completed** 2023-05-27 16:01 UTC

**Comment by AstroShogun** [comment] 2023-05-27 22:55
>closes the issue
>refuses to elaborate

**Comment by piqle** [comment] 2023-09-06 22:29
so uhh what happened with this

**Comment by Adamantcheese** [comment] 2023-09-07 01:55
If you took a look at the duplicate, you would see that 4.13.6 still has the issue but dev has it resolved; issues are closed on a per-commit basis rather than a per-release basis because otherwise it would be very hard to track. Dunno when I'll release a new stable version.
