### ISSUE TITLE
[Feature Request] Transparent Status Bar Option

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#142] opened 2019-06-28 21:51 UTC
Similar to what Dashchan has. Makes status bar transparent, lets you see text/images at the very edge of the screen instead of the solid color of your theme when scrolling.

**Comment by Adamantcheese** [comment] 2019-06-28 21:53
Duplicate of #29.

**Closed as completed by Adamantcheese** 2019-06-28 21:53 UTC
Labels: duplicate
