### ISSUE TITLE
The replies layout is broken

### ISSUE THREAD

**Issue by That-Thing** [Adamantcheese/Kuroba#192] opened 2019-07-13 13:42 UTC
![Screenshot_20190713-093958](https://user-images.githubusercontent.com/41160238/61172448-79bf6b00-a552-11e9-9a28-d48764c66424.png)

**Comment by Adamantcheese** [comment] 2019-07-13 19:37
Duplicate of #179 and #185.

**Closed as completed by Adamantcheese** 2019-07-13 19:37 UTC
Labels: duplicate
