### ISSUE TITLE
2ch: failed to show image error when opening some images

### ISSUE THREAD

**Issue by fgsfds** [Adamantcheese/Kuroba#847] opened 2020-04-03 09:23 UTC
![Screenshot_2020-04-03-14-19-43-078_com github adamantcheese chan](https://user-images.githubusercontent.com/4870330/78345009-a458c480-75b6-11ea-8368-9a1d51af49e6.jpg)

**Comment by Adamantcheese** [comment] 2020-04-03 20:04
Duplicate of #839.

**Closed as completed by Adamantcheese** 2020-04-03 20:04 UTC
Labels: duplicate
