### ISSUE TITLE
All posts in a thread are missing

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1047] opened 2020-08-06 07:39 UTC
I've made issues talking the OP and a few other posts being gone, but today I found a thread with every post not showing up. I just see the refresh button at the top of the screen.

**Comment by Adamantcheese** [comment] 2020-08-06 08:28
Duplicate of #968 probably; without any logs I can't do anything anyways because I don't know if the server just sent a bunch of garbage. Reloading the thread tosses out any cached information so it would be completely fresh; if you're not seeing anything, the server is likely at fault for that thread.

**Closed as completed by Adamantcheese** 2020-08-06 08:28 UTC
Labels: duplicate
