### ISSUE TITLE
Report "[Feature Request] Post automatically after countdown"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1043] opened 2020-08-05 06:44 UTC
UUID: 662a0c304a8df24a5460f6a3c9ede3a5
Build flavor: stable
Version name: v4.13.6
OS info: Android 9, sdk version: 28
Report description: It would be nice if this was an option, specially if you could jump to another thread in the meantime, instead of just having to sit there and wait it to be over, while counting down on your head.

**Comment by Adamantcheese** [comment] 2020-08-05 08:26
Duplicate of #337 and #89. I maintain my stance on this feature.

**Closed as completed by Adamantcheese** 2020-08-05 08:26 UTC
Labels: wontfix, report/crash report
