### ISSUE TITLE
Viewing transparent images aren't transparent

### ISSUE THREAD

**Issue by shiimizu** [Adamantcheese/Kuroba#1096] opened 2020-09-11 01:57 UTC
Is it just me? It wasn't like this before. I'm on latest dev.

1. Go to any post that that attached a transparent image (png)
1. Press the thumb to view the full image
1. The background is supposed to be transparent

**Comment by Adamantcheese** [comment] 2020-09-11 02:26
Duplicate of #1063.

**Closed as completed by Adamantcheese** 2020-09-11 02:26 UTC
Labels: duplicate

**Comment by shiimizu** [comment] 2020-09-11 02:45
Oh it was in appearance settings. Thanks!
