### ISSUE TITLE
Report "Just attach this to the scroll position report"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1325] opened 2021-07-26 07:14 UTC
UUID: 2394a9a43d1ed3fcf2cf7b0a22f42de9
Build flavor: dev
Version name: v4.13.6-1d48096
OS info: Android 10, sdk version: 29
Report description: https://files.catbox.moe/4gj7h6.mp4

**Comment by Adamantcheese** [comment] 2021-07-26 08:06
Duplicate of #1201.

**Closed as completed by Adamantcheese** 2021-07-26 08:06 UTC
Labels: duplicate
