### ISSUE TITLE
Crash report "crashes after opening a thread"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1141] opened 2020-11-04 09:58 UTC
UUID: f2e6784ecf183459b433288947708ff5
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: thread had a picture of a red exclamation mark
Logs:
```
I/Kuroba | WakeManager: Started background alarm with an interval of 15 minutes
E/Kuroba | NetUtils: Error loading bitmap from https://i.4cdn.org/3/1604463148397s.jpg
E/Kuroba | ImageViewerController: onBitmapFailure for preview in transition, cannot show correct transition bitmap
E/Kuroba | ImageViewerController: java.io.IOException: canceled due to java.lang.IllegalArgumentException: port out of range:-1
E/Kuroba | ImageViewerController: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530)
E/Kuroba | ImageViewerController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | ImageViewerController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | ImageViewerController: 	at java.lang.Thread.run(Thread.java:919)
E/Kuroba | ImageViewerController: 	Suppressed: java.lang.IllegalArgumentException: port out of range:-1
E/Kuroba | ImageViewerController: 		at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
E/Kuroba | ImageViewerController: 		at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
E/Kuroba | ImageViewerController: 		at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
E/Kuroba | ImageViewerController: 		at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
E/Kuroba | ImageViewerController: 		at java.security.AccessController.doPrivileged(AccessController.java:43)
E/Kuroba | ImageViewerController: 		at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.RouteSelector$resetNextProxy$1.invoke(RouteSelector.kt:106)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.kt:113)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.kt:53)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:202)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
E/Kuroba | ImageViewerController: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
E/Kuroba | ImageViewerController: 		... 3 more
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: port out of range:-1
E/Kuroba | UNCAUGHT: 	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
E/Kuroba | UNCAUGHT: 	at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
E/Kuroba | UNCAUGHT: 	at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
E/Kuroba | UNCAUGHT: 	at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
E/Kuroba | UNCAUGHT: 	at java.security.AccessController.doPrivileged(AccessController.java:43)
E/Kuroba | UNCAUGHT: 	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.RouteSelector$resetNextProxy$1.invoke(RouteSelector.kt:106)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.kt:113)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.kt:53)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:202)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
E/Kuroba | UNCAUGHT: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
E/Kuroba | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:919)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 29
E/Kuroba | UNCAUGHT: App Version: v4.13.6
E/Kuroba | UNCAUGHT: Phone Model: HMD Global Nokia 6.1
I/Kuroba | WakeManager: Started background alarm with an interval of 15 minutes
```

**Comment by Adamantcheese** [comment] 2020-11-05 02:30
Duplicate of #1140.

**Closed as completed by Adamantcheese** 2020-11-05 02:30 UTC
Labels: report/crash report
