### ISSUE TITLE
Status bar goes darker after using the app for a little bit

### ISSUE THREAD

**Issue by Iggin20** [Adamantcheese/Kuroba#25] opened 2019-06-04 19:02 UTC
![Screenshot_20190604-145203](https://user-images.githubusercontent.com/51381714/58905873-c2287500-86d8-11e9-8027-de9b5b86735d.png)
This happens when using the light theme on a Pixel 2 XL. It goes back to the correct color after restarting the app but it eventually always goes back to this.

**Comment by Adamantcheese** [comment] 2019-06-05 03:22
The Pixel 2 and Pixel 2 XL emulators I used couldn't reproduce this issue.

**Comment by Iggin20** [comment] 2019-06-05 03:44
I looked into it more, I think it happens to me after I do some stuff (open images/webms, post, etc). This could just be an issue on my phone though for all I know.

**Comment by Adamantcheese** [comment] 2019-06-05 03:50
Still can't reproduce the issue.

**Comment by K1rakishou** [comment] 2019-06-05 07:12
I have Pixel 2 XL too and I managed reproduce it. It happens when you open the reply chain couple of times. It gets gradually darker every time you open it. Looks like the method that should set the old color of the status bar is not getting called.

**Comment by Iggin20** [comment] 2019-06-05 18:50
Yeah, that seems to be the issue

**Comment by Adamantcheese** [comment] 2019-06-06 00:04
Confirming that opening/closing the replies popup changes the status bar color.

**Closed as completed** 2019-06-06 00:15 UTC
Labels: bug
