### ISSUE TITLE
Exported settings don't properly return hidden/removed threads

### ISSUE THREAD

**Issue by calactic** [Adamantcheese/Kuroba#1347] opened 2021-08-25 11:09 UTC
Due to issue 1345, I've had to roll back to the last properly working apk due to crashing on launch after rolling back without uninstalling, but I've found that my back up of my settings hasn't kept my hidden/removed threads as hidden/removed. 

Upon trying to remove an already removed thread, the catalog reloads and the thread isn't removed. I had to to settings and select clear all thread hides to be able to remove already removed threads again. 

Backup made in c832bc44, restored to 3e9528b.

**Comment by Adamantcheese** [comment] 2021-09-09 05:21
Duplicate of #1322.

**Closed as completed by Adamantcheese** 2021-09-09 05:21 UTC
Labels: bug, duplicate
