### ISSUE TITLE
[BUG/tweak?] loading bar is now black, unable to see loading progress.

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#967] opened 2020-07-01 02:18 UTC
In the previous version the loading bar was white, making it clear enough to see the progress of loading media. Now in the new version its pitch black and the only way to somewhat see it depends on the color of the content. 

Version: 4.13.4
OS: Android 10
Device: Galaxy S10

**Comment by Adamantcheese** [comment] 2020-07-01 03:38
Duplicate of #965. I suspect that this is going to show up a lot so I'll change the loading bar to not use the accent color and instead be a light grey, as the image viewer always is on a black background.

**Closed as completed** 2020-07-01 04:50 UTC
Labels: duplicate, enhancement
