### ISSUE TITLE
[BUG] Large size images failing to load

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#472] opened 2019-12-20 19:34 UTC
I have recently started to notice that large size images (approx. 3.5MB+) will occasionally fail to load and throw an error. You can clearly tell when an image will fail to load because the loading progress bar will keep resetting it's progress, see video (at 0:21, 0:42, 1:02, curiously it's happens at around 20 sec intervals, might mean something?):
https://streamable.com/72syu

At this point, if you tap to close the image you will get a "Failed to show image" error message. If you just keep waiting instead of closing the image manually the error message is "Failed to show image. Deep-zoom loading failed." From a quick comparison it doesn't seem to be happening on Clover, even when loading is very slow (20+ seconds), it doesn't fail loading images.

Here's the logs (although Pastebin seems to be down at this very moment):
https://pastebin.com/8QPmE1S4

**Comment by Adamantcheese** [comment] 2019-12-20 20:21
Duplicate of #458.

**Closed as completed by Adamantcheese** 2019-12-20 20:21 UTC
Labels: duplicate

**Comment by K1rakishou** [comment] 2019-12-21 07:20
All such problems should be fixed when https://github.com/Adamantcheese/Kuroba/pull/449 is done.
