### ISSUE TITLE
SnackbarLayout is still leaking

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#671] opened 2020-02-18 07:43 UTC
UUID: e3fd44e11674872682fdd22b9bc84be6
Build flavor: dev
Version name: v4.11.0-e6c1909
OS info: Android 10, sdk version: 29
Report description:
Logs:
```
в”¬в”Ђв”Ђв”Ђ
в”‚ GC Root: System class
в”‚
в”њв”Ђ android.view.accessibility.AccessibilityManager class
в”‚    Leaking: NO (a class is never leaking)
в”‚    в†“ static AccessibilityManager.sInstance
в”‚                                  ~~~~~~~~~
в”њв”Ђ android.view.accessibility.AccessibilityManager instance
в”‚    Leaking: UNKNOWN
в”‚    в†“ AccessibilityManager.mTouchExplorationStateChangeListeners
в”‚                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
в”њв”Ђ android.util.ArrayMap instance
в”‚    Leaking: UNKNOWN
в”‚    в†“ ArrayMap.mArray
в”‚               ~~~~~~
в”њв”Ђ java.lang.Object[] array
в”‚    Leaking: UNKNOWN
в”‚    в†“ Object[].[0]
в”‚               ~~~
в”њв”Ђ androidx.core.view.accessibility.AccessibilityManagerCompat$TouchExplorationStateChangeListenerWrapper instance
в”‚    Leaking: UNKNOWN
в”‚    в†“ AccessibilityManagerCompat$TouchExplorationStateChangeListenerWrapper.mListener
в”‚                                                                            ~~~~~~~~~
в”њв”Ђ com.google.android.material.snackbar.BaseTransientBottomBar$SnackbarBaseLayout$1 instance
в”‚    Leaking: UNKNOWN
в”‚    Anonymous class implementing androidx.core.view.accessibility.AccessibilityManagerCompat$TouchExplorationStateChangeListener
в”‚    в†“ BaseTransientBottomBar$SnackbarBaseLayout$1.this$0
в”‚                                                  ~~~~~~
в”њв”Ђ com.google.android.material.snackbar.Snackbar$SnackbarLayout instance
в”‚    Leaking: YES (View.mContext references a destroyed activity)
в”‚    mContext instance of android.view.ContextThemeWrapper, wrapping activity com.github.adamantcheese.chan.StartActivity with mDestroyed = true
в”‚    View#mParent is null
в”‚    View#mAttachInfo is null (view detached)
в”‚    View.mWindowAttachCount = 0
в”‚    в†“ Snackbar$SnackbarLayout.mContext
в”њв”Ђ android.view.ContextThemeWrapper instance
в”‚    Leaking: YES (Snackbar$SnackbarLayoutв†‘ is leaking and ContextThemeWrapper wraps an Activity with Activity.mDestroyed true)
в”‚    в†“ ContextThemeWrapper.mBase
в•°в†’ com.github.adamantcheese.chan.StartActivity instance
вЂ‹     Leaking: YES (ObjectWatcher was watching this because com.github.adamantcheese.chan.StartActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
вЂ‹     key = 92b0e1c2-1342-4e6c-b31a-167b69e4bfb7
вЂ‹     watchDurationMillis = 5271
вЂ‹     retainedDurationMillis = 256

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Google
LeakCanary version: 2.2
App process name: com.github.adamantcheese.chan.dev
Analysis duration: 6627 ms
```

**Comment by K1rakishou** [comment] 2020-02-18 07:43
I remember there was an attempt to fix this but it still keeps happening in the latest dev builds.

**Comment by Adamantcheese** [comment] 2020-02-18 07:44
Duplicate of #583, #581, and probably some other one. Don't report this again.

**Closed as completed by Adamantcheese** 2020-02-18 07:44 UTC
Labels: duplicate, wontfix, report/crash report

**Comment by K1rakishou** [comment] 2020-02-18 07:45
But we need to do something with it.

**Comment by Adamantcheese** [comment] 2020-02-18 07:52
We don't have to do anything about it if it's not fucking possible to figure out what Snackbar instance is holding onto crap. If you want to do it, be my guest, but I really don't care about this one.

**Comment by Adamantcheese** [comment] 2020-02-18 07:53
I almost guarantee you that this "memory leak" will appear anytime you close the application when a Snackbar is on the screen.

**Comment by K1rakishou** [comment] 2020-02-18 08:00
Nah, apparently it's the other way around. It happens when you create a snackbar but never show it.
https://github.com/material-components/material-components-android/issues/497
https://stackoverflow.com/questions/57338450/memory-leak-due-to-snackbar
