### ISSUE TITLE
[REPORT] View new posts bar appear when making a new post and glitches the app

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#695] opened 2020-02-22 13:56 UTC
UUID: 6f3c68a78e15bee735ccca07d4d47d23
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: When you make a new post the new post bar (the one that appears at the bottom counting how many new posts have been made since you went into the specific thread) appear, making the app have a weird behaviour. Investigate on this problem.

**Comment by Adamantcheese** [comment] 2020-02-22 22:43
Likely a duplicate of #674. Also that's not enough information for me to know what to even look for? Just "weird behavior" doesn't tell me what's wrong.

**Closed as completed by Adamantcheese** 2020-02-22 22:43 UTC
Labels: duplicate, report/crash report
