### ISSUE TITLE
[IMPROVEMENT] Support for [math] for boards like /sci/

### ISSUE THREAD

**Issue by svin24** [Adamantcheese/Kuroba#404] opened 2019-11-03 22:19 UTC
So boards like /sci/ have this cool thing like a spoiler but it parses math.
We should get this in.

**Comment by Adamantcheese** [comment] 2019-11-04 06:25
Duplicate of #137, but I'll see what can be done; I might be able to hotlink a rendered math tag into the images, rather than inlining it.

**Closed as completed** 2020-08-14 05:08 UTC
Labels: enhancement
