### ISSUE TITLE
[bug] App crash when saving image via gallery.

### ISSUE THREAD

**Issue by debagos** [Adamantcheese/Kuroba#1369] opened 2021-10-02 13:12 UTC
When I open an image gallery in an (4chan) thread, view any image and then touch the save icon, the app crashes.
It happens every singel time, but it only happens when saving images opened via the image gallery. All other save methods do work fine.

Some settings that may be relevant:
- `"Save images in board folders"` = true / checked
- `"Save images in thread folders"` = true / checked
- `"Save server filename"` = true / checked

My Kuroba version:
`Kuroba-dev v4.13.6-34a61da1` (latest dev version released on 10th September 2021)

**Comment by Adamantcheese** [comment] 2021-10-02 19:17
Considering that I have the same exact settings enabled and I have no crashes, I need additional info. You can go to Developer Settings -> View Logs and copy them into here so I can see the crash stack trace, which will give me the most info.

**Comment by debagos** [comment] 2021-10-03 17:11
Ah thanks, didn't knew about the log viewer.
Here is the error message:
```
Called from unhandled exception handler.
java.lang.UnsupportedOperationException
	at com.github.adamantcheese.chan.ui.controller.AlbumViewController.getPostForPostImage(AlbumViewController.java:151)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.appendAdditionalSubDirectories(ImageViewerController.java:313)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveShare(ImageViewerController.java:281)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveClicked(ImageViewerController.java:228)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.lambda$Gz-89eDToQVexSOaWvGSnEF0dtc(Unknown Source:0)
	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ImageViewerController$Gz-89eDToQVexSOaWvGSnEF0dtc.onClick(Unknown Source:2)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuItem.performClick(ToolbarMenuItem.java:209)
	at com.github.adamantcheese.chan.ui.toolbar.-$$Lambda$XkVMUVrFUsNlqIK8NbX-1gYdRjU.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
------------------------------
END OF CURRENT RUNTIME MESSAGES
------------------------------
Android API Level: 28
App Version: v4.13.6-34a61da1
```
I hope that's enough information for you to reproduce and/or hunt the bug down.
If not, let me know, then I will give you an redacted verbose log.

Thanks in advance!

**Comment by Adamantcheese** [comment] 2021-10-03 19:05
Ah, duplicate of #1349.

**Closed as completed by Adamantcheese** 2021-10-03 19:05 UTC
Labels: bug, duplicate, cantrepro
