### ISSUE TITLE
[Feature Request] Post queueing 

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#337] opened 2019-08-26 14:42 UTC
Now that we have Captcha queueing it would make sense to implement this feature. Here's how it could work:
1. Post a reply. The new reply cooldown timer appears on the post button (or somewhere else in the reply layout) and starts counting down.
2. Write another post and click the post button again. Whatever is in the reply box will now be automatically posted once the countdown reaches zero (given there is a valid Captcha solved) without any further input required from the user.

**Comment by ownBard** [comment] 2019-08-26 23:08
Duplicate of #89

**Closed as completed** 2019-08-26 23:30 UTC
Labels: duplicate

**Comment by Astridchan** [comment] 2019-08-27 06:53
>Duplicate of #89

Yeah, but that issue was opened and closed months before captcha queueing was implemented, I thought the circumstances have changed enough to justify opening a new feature request for this feature.

@Adamantcheese
Could you reconsider your stance on this feature? It would be extremely convenient to be able to queue your next post and have it posted automatically rather than wait the cooldown every time to click the post button. In #89 you said you don't want to implement image dumping because it would create spam but you could just make it so it only allows for one post queued at a time.
