### ISSUE TITLE
New board /vt/ added won't appear

### ISSUE THREAD

**Issue by HNKMaster** [Adamantcheese/Kuroba#1237] opened 2021-01-29 14:40 UTC
Just now there's a new board (/vt/) and it doesn't appear on the app, even when force stopping it and restarting the phone.

**Comment by Adamantcheese** [comment] 2021-01-29 21:52
Duplicate of #1032. It's working fine, both stable and dev.
![Screenshot_20210129-124434](https://user-images.githubusercontent.com/9031585/106330988-0d41b500-6239-11eb-94f2-cc4b072d4806.jpg)

**Closed as completed by Adamantcheese** 2021-01-29 21:52 UTC
Labels: duplicate
