### ISSUE TITLE
Report ""view removed posts" in the thread top menu doesn't do anything"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1356] opened 2021-09-03 09:28 UTC
UUID: 189f97a5cdda42c0baf223db018be36a
Build flavor: dev
Version name: v4.13.6-c832bc44
OS info: Android 9, sdk version: 28
Report description: posts which have been deleted continue to show anyway, so idk if maybe it's meant to show posts which have been hidden and removed by a filter? that would be useful

**Comment by Adamantcheese** [comment] 2021-09-09 05:18
Viewing removed posts is only for posts that have been removed by a filter or manually. Duplicate of #1347, or at least related enough that I'm combining the issues.

**Closed as completed by Adamantcheese** 2021-09-09 05:18 UTC
Labels: duplicate
