### ISSUE TITLE
[FEATURE] Fullscreen gallery viewer aka immersive mode

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#168] opened 2019-07-06 10:07 UTC
People are asking, so why not implement it.

**Comment by ownBard** [comment] 2019-07-06 10:22
Also a duplicate of #22

**Comment by K1rakishou** [comment] 2019-07-06 10:55
Well it kinda is but not exactly. The other issue is about making fullscreen gallery toggleable with a button while the #169 will make it always appear fullscreen if the setting is turned on.

**Closed as completed** 2019-07-09 01:35 UTC
Labels: enhancement

**Comment by Adamantcheese** [comment] 2019-07-09 01:37
I almost guarantee people are going to complain about the nav bar still being shown, but it works.

**Comment by K1rakishou** [comment] 2019-07-09 07:04
>about the nav bar still being shown

What? It shouldn't.

**Comment by Adamantcheese** [comment] 2019-07-09 07:09
I mean the in-app one, not the status bar.

**Comment by K1rakishou** [comment] 2019-07-09 07:15
Oh, you mean the Toolbar. I actually dunno should it be hidden as well or not. Lets see what people will say.
