### ISSUE TITLE
[feature request] bring back the dropdown menu for quoting

### ISSUE THREAD

**Issue by coty-crg** [Adamantcheese/Kuroba#1085] opened 2020-08-31 16:16 UTC
Clicking the post number is awkward on mobile.

**Comment by Adamantcheese** [comment] 2020-09-01 01:29
Duplicate of #1023. I like the implication that "on mobile" isn't the standard usage of the app and you're posting from like a smart fridge or treadmill or, somehow, a car.

**Closed as completed by Adamantcheese** 2020-09-01 01:29 UTC

**Comment by coty-crg** [comment] 2020-09-01 15:32
The commit revert implies its coming back in a future update, yeah? Thanks.

Also, you don't use Kuroba in your tesla? wtf

**Comment by Adamantcheese** [comment] 2020-09-02 01:54
Android Auto support soon™. But not really because it's kinda locked down what can run on a car, see https://developer.android.com/docs/quality-guidelines/car-app-quality. "Apps don't work with Android Auto unless they are installed from the Play Store."
Shame really, would've been fun to test out.
