### ISSUE TITLE
[Feature Request] Prevent thread from autowatching

### ISSUE THREAD

**Issue by Nachtalb** [Adamantcheese/Kuroba#1060] opened 2020-08-13 12:10 UTC
The problem I have in general is that on certain long-running boards threads may match an auto watch regex even though you don't want this to happen. Every time you start the app that thread get's watched again and you get unnecessary notifications. I'd love to see a way to stop these threads from being watched again. 

Of course, it's possible to make an auto watch regex more complex. But in my experience, it only makes stuff slower the more complex a regex is, especially if you use `*` or `+` or other edge cases. It's hard to write a regex without one of those when the excluding words can appear in any position before and after the words you actually want to match for. 
Eg. I already had regex performance problems with other 4chan android clients (there as filters and not auto watch). And there are other examples like this here: https://stackoverflow.com/a/22650620/5699307 and many more. 

So instead of making the regex more complicated and expensive to run, I propose that it'll be possible to stop a  thread to be auto watched again. This could e.g. be done via the three-dot menu in when having the thread open or simply by a swiping auto watched threads away from the bookmark list. Though I think the first option is safer and can't really happen accidentally.

**Comment by Adamantcheese** [comment] 2020-08-15 06:04
Swiping away a thread that was filter-watched in the bookmarks menu should make sure it doesn't come back; the filter watch implementation has always had an ignore set internally to make sure that they don't get watched again. This is even persisted between application restarts. The only time that the internal ignored posts set is cleared is if it fills up with post numbers from non-filterwatch catalog loads (ie normal browsing). That threshold is 650 unique posts, which is like 11 catalogs. Since it's a set, reloading a catalog that was already added in before shouldn't activate a purge because it'll only add in a few posts at most.

If you're finding that you're getting re-filter watches constantly, then that internal set is being purged a lot. If you're noticing that ignored stuff isn't being kept between restarts and stuff is immediately coming back, then that's a bug. If you could tell me in a bit more detail what's actually happening, then I can help fix that problem. Note that I use filter watches constantly to keep track of rarely appearing threads or some long-running stuff on boards like /c/, and I haven't had too much trouble with the implementation, but I also keep the application locked and running basically 24/7.

**Comment by Adamantcheese** [comment] 2020-09-01 08:27
Closing as no additional input has been provided, everything's working as intended then.

**Closed as completed by Adamantcheese** 2020-09-01 08:27 UTC
Labels: bug, question

**Comment by Nachtalb** [comment] 2020-09-05 23:58
Sorry for not replying, I forgot I had created this issue 😅

About the max catalog number. I have 13 boards setup in total over 3 different chans (8:2:3). 
I have 1 watch filter that acts on 1 board, 2 highlight filters that act on 2 boards (1 of them is the same as watch filter) and last but not least 7 remove filters from which some act on all boards.

The only way I could see this catalog set being filled up is either by not removing dead threads from the set or it reload all catalogs. Because usually I brows on about 2-4 boards so I don't think it should be filled up by that.if it'd be the second case with reloading all catalogs... why, we should only reload the ones where we are on and have watch filters set, the rest is unnecessary. If it'd be the former one then it'd just be a bug I guess. 

Either way on my end it readds the threads right on the next catalog update ( don't even have to restart ).

Also why is there a limit to that set? If it is somewhat efficiently made with just a few metadata per entry or just the ignore mapping then there should be no reason for limiting it, neither performance nor ram usage should be a problem.
