### ISSUE TITLE
Report "4chan pass"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1281] opened 2021-05-27 10:08 UTC
UUID: 12b13a8f6ccde58295e915f88e438700
Build flavor: dev
Version name: v4.13.6-3e58cd9
OS info: Android 10, sdk version: 29
Report description: Can't log out from pass. Clicking logout shows the token and key field, however a new input cannot be submitted and navigating back shows the app still thinks you're logged in.
My current token is expired which may also have something to do with it.

**Comment by Adamantcheese** [comment] 2021-05-28 01:24
Duplicate of #1269.

**Closed as completed by Adamantcheese** 2021-05-28 01:24 UTC
Labels: duplicate
