### ISSUE TITLE
Crash to home screen when creating a thread

### ISSUE THREAD

**Issue by zetapulse** [Adamantcheese/Kuroba#406] opened 2019-11-06 04:09 UTC
Kuroba crashes to home screen when I create a thread.
When I reopen it, my thread has been created and bookmarked, but the bookmark thumbnail image is the OP image of another thread on the same board. The thumbnail is corrected when re-bookmarking my thread.

**Comment by Adamantcheese** [comment] 2019-11-06 05:15
Duplicate of #405.

**Closed as completed by Adamantcheese** 2019-11-06 05:15 UTC
Labels: duplicate
