### ISSUE TITLE
Report "highlight posts by this id"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1138] opened 2020-11-04 07:15 UTC
UUID: 0b90760680ca81d7c1fdbe596084f0e5
Build flavor: stable
Version name: v4.13.6
OS info: Android 11, sdk version: 30
Report description: can you make them a unique colour again. when they're the same colour as my posts it makes it needlessly hard to easily view which posts were made by the highlighted id.

also please make a toggle on the new high contrast id colours. you didn't even use the same colours as the actual site.

**Comment by Adamantcheese** [comment] 2020-11-04 08:03
Duplicate of #1095. The rest I don't care for.

**Closed as completed by Adamantcheese** 2020-11-04 08:03 UTC
Labels: report/crash report
