### ISSUE TITLE
[BUG] Reply button shows up in local threads

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#311] opened 2019-08-19 07:57 UTC
It shouldn't.
TODO: update testing guide.

**Comment by K1rakishou** [comment] 2019-08-19 09:46
Oh, it actually shows up in the fully downloaded threads too.

**Comment by Adamantcheese** [comment] 2019-08-21 00:12
This is probably an issue with a change I made to the button to support bottom inputs; it might be a dupe of another issue as well, but I need to take a look.

**Closed as completed** 2019-08-24 01:26 UTC
Labels: bug
