### ISSUE TITLE
Report "updating app"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#920] opened 2020-06-08 06:08 UTC
UUID: 3c93865b9c0af630e479f9589599a4ce
Build flavor: dev
Version name: v4.12.0-b1963c3
OS info: Android 7.1.1, sdk version: 25
Report description: app auto crashes on update option

**Comment by Adamantcheese** [comment] 2020-06-10 03:05
Yeah this isn't enough info at all, and I can't reproduce it either, emulator or hardware.

**Comment by Adamantcheese** [comment] 2020-06-11 03:22
Probably the same as #926, closing.

**Closed as completed by Adamantcheese** 2020-06-11 03:22 UTC
Labels: cantrepro, report/crash report
