### ISSUE TITLE
Images getting greyed out on the catalog

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#1052] opened 2020-08-09 22:06 UTC
Sometimes images will end up looking like this when scrolling too fast. Only reloading the catalog makes them look normal again.
![Screenshot_20200809-190215_Kuroba](https://user-images.githubusercontent.com/29208110/89742772-40b63a80-da73-11ea-9933-da43883f313d.png)

**Comment by Adamantcheese** [comment] 2020-08-10 04:33
Duplicate of #1006.

**Closed as completed by Adamantcheese** 2020-08-10 04:33 UTC
Labels: duplicate
