### ISSUE TITLE
YouTube titles & durarions

### ISSUE THREAD

**Issue by zibbi** [Adamantcheese/Kuroba#1129] opened 2020-10-27 06:39 UTC
YouTube titles retuning "null"

Edit: It turned out it only happened in /fit/ that's where the links of "YouTube" only return "null" but the other boards such as pol etc... weren't getting this error and the links were getting their titles and durations right, I don't know why it only happens in /fit/ but the this error doesn't happen in the other boards.

Edit: Now it's partially working, some of them are null and some of them works, but the problem is that all of the links are in the "youtu.be" form and yet some are working and some are "null".

![](https://i.imgur.com/QC0gKuu.jpg)

**Comment by Adamantcheese** [comment] 2020-10-28 05:46
I'm assuming that you're on dev; if you are, I've changed the way that cached titles/durations are stored, so the re-constructed embed objects are all nulled out probably. There's a developer button to clear cached titles/durations that should get rid of that bad data. It's really the only thing I can think of because otherwise titles are never null. Gonna close this anyways because I can't reproduce it.

**Closed as completed by Adamantcheese** 2020-10-28 05:46 UTC
