### ISSUE TITLE
Memory leak on dev

### ISSUE THREAD

**Issue by ugaugabuga** [Adamantcheese/Kuroba#666] opened 2020-02-16 17:37 UTC
```
`┬───
│ GC Root: System class
│
├─ android.view.accessibility.AccessibilityManager class
│    Leaking: NO (a class is never leaking)
│    ↓ static AccessibilityManager.sInstance
│                                  ~~~~~~~~~
├─ android.view.accessibility.AccessibilityManager instance
│    Leaking: UNKNOWN
│    ↓ AccessibilityManager.mTouchExplorationStateChangeListeners
│                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
├─ java.util.concurrent.CopyOnWriteArrayList instance
│    Leaking: UNKNOWN
│    ↓ CopyOnWriteArrayList.elements
│                           ~~~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    ↓ Object[].[0]
│               ~~~
├─ androidx.core.view.accessibility.AccessibilityManagerCompat$TouchExplorationStateChangeListenerWrapper instance
│    Leaking: UNKNOWN
│    ↓ AccessibilityManagerCompat$TouchExplorationStateChangeListenerWrapper.mListener
│                                                                            ~~~~~~~~~
├─ com.google.android.material.snackbar.BaseTransientBottomBar$SnackbarBaseLayout$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing androidx.core.view.accessibility.AccessibilityManagerCompat$TouchExplorationStateChangeListener
│    ↓ BaseTransientBottomBar$SnackbarBaseLayout$1.this$0
│                                                  ~~~~~~
├─ com.google.android.material.snackbar.Snackbar$SnackbarLayout instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    mContext instance of android.view.ContextThemeWrapper, wrapping activity com.github.adamantcheese.chan.StartActivity with mDestroyed = true
│    View#mParent is null
│    View#mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 0
│    ↓ Snackbar$SnackbarLayout.mContext
├─ android.view.ContextThemeWrapper instance
│    Leaking: YES (Snackbar$SnackbarLayout↑ is leaking and ContextThemeWrapper wraps an Activity with Activity.mDestroyed true)
│    ↓ ContextThemeWrapper.mBase
╰→ com.github.adamantcheese.chan.StartActivity instance
​     Leaking: YES (ObjectWatcher was watching this because com.github.adamantcheese.chan.StartActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = 22a5d7a1-628f-4ea1-b54d-5e0e62fb8a19
​     watchDurationMillis = 5301
​     retainedDurationMillis = 298
```

METADATA

Build.VERSION.SDK_INT: 24
Build.MANUFACTURER: HUAWEI
LeakCanary version: 2.2
App process name: com.github.adamantcheese.chan.dev
Analysis duration: 43726 ms`

**Comment by Adamantcheese** [comment] 2020-02-16 23:15
Duplicate of #583, #581. Probably not solvable, but very minor anyways.

**Closed as completed by Adamantcheese** 2020-02-16 23:15 UTC
Labels: duplicate
