### ISSUE TITLE
images frequently error in catalog mode

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#977] opened 2020-07-05 06:01 UTC
Setting catalog mode and increasing column count causes most images to error if I scroll fast enough. Even if I scroll normally a couple here and there tend to fail.
Tested on v.4.13.4-6d44efd using a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment] 2020-07-06 05:13
Duplicate of  #966.

**Closed as completed by Adamantcheese** 2020-07-06 05:13 UTC
Labels: duplicate
