### ISSUE TITLE
Cannot highlight text on long press when viewing a reply to a post

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#865] opened 2020-04-28 11:08 UTC
Specifically when viewing the replies to a post it is impossible to highlight text if the window is too small. To my knowledge, if the post is long enough or if there are multiple replies this isn't an issue
Testing this is a hassle because removing/hiding posts doesn't change them in this menu.

Using kuroba dev v4.12.0-db0938f on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment] 2020-05-09 06:23
There's nothing wrong here, all text is selectable. If you find it hard to select, you can change the text size or use a stylus.

**Comment by ghost** [comment] 2020-05-10 05:36
There is definitely a bug here, I don't know why you would say that.
I came back to this to see what causes it, and it seems that the culprit is "Shift post format".
With the setting left default, nothing breaks. However, when I turn it off, I can only select text from reply windows with multiple replies.

**Comment by lewri** [comment] 2020-05-17 07:16
After some testing I can reproduce this error in the latest stable build (4.12.0)

![Screenshot_20200517_081109_com github adamantcheese chan](https://user-images.githubusercontent.com/20030128/82138154-28d56e80-9816-11ea-8730-6f29d0a96985.jpg)
https://boards.4chan.org/ck/thread/14090887

Go to post 14092163 (bottom of photo) and open the "1 reply". Text can't be selected by long press where shift post comment is off.

Actually just doing that seems to break a lot of single replys from being selected.

Nothing in the logs.

**Comment by Adamantcheese** [comment] 2020-05-17 08:22
Again, I cannot replicate this issue. Hardware or software; there will be nothing in the logs because this isn't something that would have any debug logging associated with it. If you mean something like #202 or #425, that's an Android platform issue that has a workaround in it, but unfortunately I can't really do anything about otherwise.
![Screenshot_20200517-010313](https://user-images.githubusercontent.com/9031585/82139379-379f2f80-97dc-11ea-8fb9-6aa750bb2965.jpg)

**Comment by lewri** [comment] 2020-05-17 11:34
I'm not fully convinced it is an Android issue. It's a specific behaviour in the app when you click on a post which has "1 reply".  The fact the issue is resolved by turning on the "shift comments" option makes me think it's something to do with how the replies window shows 1 reply.  It may be worth checking to see if other people are getting the issue too. There are two workarounds built into the app though. But a workaround is not a fix.

The OPs Android version will be 10 or 11. Whereas mine is  9.

I'm using an Honor 9 whereas OP runs a Samsung.

There's nothing in common between the two to suggest it could be an Android fault. I'm not entirely sure why you're free of the bug though.

**Comment by lewri** [comment] 2020-05-17 14:39
Just to add I've also been able to reproduce the fault on Android 8 using a tablet.

Also just double checked  202 and 425. Those relate to the text input box for replies. This issue concerns viewing replies from a post.

**Comment by Adamantcheese** [comment] 2020-05-17 23:28
I've changed the popup implementation to use the same RecyclerView/PostAdapter as the rest of the application, as it seems to have been using a ListView/ArrayAdapter, which per the documentation isn't a well supported configuration. Again, I don't have a way to test if that fixed it, so you'll have to tell me.

**Comment by lewri** [comment] 2020-05-18 08:32
Cheers but I cant test. Tried on two devices. The app closes itself after the clover logo is on the screen for a few seconds.

Trying to use the APK from here: https://kuroba.io:8443/apk/41200_35d253041d9f43778d4e45e8e7e9ba1cb211de2e.apk

Edit: looks like bug #878 ; pasted the logcat in there for you.

**Comment by Adamantcheese** [comment] 2020-05-19 04:48
@lewri I've done some changes to #878 that should allow you to test the fix here; if things are still broken and the app won't start, mention it either here or in the other issue. Thanks for the help!

**Comment by Adamantcheese** [comment] 2020-05-19 04:57
@clawyf You're free to test out as well; appreciate the help greatly.

**Comment by lewri** [comment] 2020-05-19 13:15
Yep working now. And the fix works at least on my phone. Great work Adamentcheese :)

Edit: Also working on tablet

**Comment by ghost** [comment] 2020-05-19 13:25
From what I can tell, updating the app has completely fixed the issue. I'll test some more later today.

**Comment by Adamantcheese** [comment] 2020-05-20 02:31
Closed as of 40ce675, greatly appreciated for the help.

**Closed as completed by Adamantcheese** 2020-05-20 02:31 UTC
Labels: bug, cantrepro
