### ISSUE TITLE
Crash while uploading a thread

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#407] opened 2019-11-06 20:26 UTC
```E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: get() only works for transient loadables
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.database.DatabaseLoadableManager.get(DatabaseLoadableManager.java:91)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onPostComplete(ReplyPresenter.java:362)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$4$2.onHttpSuccess(Chan4.java:423)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$4$2.onHttpSuccess(Chan4.java:420)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.http.HttpCall.lambda$callSuccess$0$HttpCall(HttpCall.java:99)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.http.-$$Lambda$HttpCall$ae4RUfdaPawOgAydPDbGyOKFoAI.run(Unknown Source:2)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:193)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.9.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
```

**Comment by Adamantcheese** [comment] 2019-11-07 01:47
Duplicate of #405 and #406. I'm pinning this so it isn't posted again, as it has already been fixed on the main branch.

**Closed as completed by Adamantcheese** 2019-11-07 01:47 UTC
Labels: duplicate
