### ISSUE TITLE
App crashes when adding another 4chan board

### ISSUE THREAD

**Issue by Vandino86** [Adamantcheese/Kuroba#1344] opened 2021-08-22 18:30 UTC
The board appears on the list of added boards after I re-open the app, but it's still pretty annoying. Here's a crashlog:

```
=== LOGS(August 22, 2021 6:21:34 PM UTC) ===
D/Kuroba-dev | UpdateManager: Calling update API
D/Kuroba-dev | ReportManager: Collected 6 crash logs
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: android.content.res.Resources$NotFoundException: String resource ID #0x0
E/Kuroba-dev | UNCAUGHT: 	at android.content.res.Resources.getText(Resources.java:512)
E/Kuroba-dev | UNCAUGHT: 	at android.content.Context.getText(Context.java:636)
E/Kuroba-dev | UNCAUGHT: 	at com.google.android.material.snackbar.Snackbar.setAction(Snackbar.java:270)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.buildCommonSnackbar(AndroidUtils.java:532)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.buildCommonSnackbar(AndroidUtils.java:540)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BoardSetupController.boardsWereAdded(BoardSetupController.java:192)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.BoardSetupPresenter.onAddDialogPositiveClicked(BoardSetupPresenter.java:130)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BoardAddLayout.onPositiveClicked(BoardAddLayout.java:114)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BoardSetupController.lambda$showAddDialog$0(BoardSetupController.java:163)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$BoardSetupController$h9GukUOG2ZORy1-E8al37L0DREk.onClick(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:246)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:8587)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 30
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-3e9528b
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-A526U1


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: content://com.android.externalstorage.documents/tree/3FDB-080B%3AKuroba-dev%2Ffiles, active: SAF
Phone layout mode: AUTO
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true

```

**Comment by Adamantcheese** [comment] 2021-08-23 05:57
Duplicate of #1334.

**Closed as completed by Adamantcheese** 2021-08-23 05:57 UTC
Labels: bug, duplicate
