### ISSUE TITLE
[Feature Request] Save last reencode settings

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#143] opened 2019-06-28 22:37 UTC
Could we have the ability to save our settings for EXIF/filename/hash scrambling so we don't have to do it every time ~and 2) have the ability to post images by pasting a URL like how 4chan X allows you to?~
I think this is the last of the things I saw requested, but I wasn't looking very hard.

**Comment by Adamantcheese** [comment] 2019-06-28 22:51
2. is a duplicate of #100.

**Closed as completed** 2019-07-13 01:48 UTC
Labels: enhancement
