### ISSUE TITLE
[Bug] With newest update, a post's content sometimes bleeds into the header (filename/post id/post time)

### ISSUE THREAD

**Issue by chausies** [Adamantcheese/Kuroba#185] opened 2019-07-10 13:38 UTC
The two kinds of examples I've run across are

1. when checking the replies for a post, sometimes the top reply bleeds into the post id / post time.
2. When the first post has a huge filename or subject, and its content is bigger than two lines, then the content can bleed into the filename/subject.

The two examples can be found in these screenshots: https://imgur.com/a/erVwOFW

For the record, this is on an LG V20, and it happens somewhat commonly.

**Comment by Adamantcheese** [comment] 2019-07-10 23:44
Duplicate of #174.

**Closed as completed by Adamantcheese** 2019-07-10 23:44 UTC
Labels: duplicate
