### ISSUE TITLE
App crashes when downloading individual images from the album

### ISSUE THREAD

**Issue by bungholemaster** [Adamantcheese/Kuroba#1387] opened 2022-01-08 15:20 UTC
On latest dev version Kuroba-dev v4.13.6-34a61da1

Batch downloading images from a thread using the album works, even just single images, but if I open the album and try to download a particular image it crashes every single time. Going to the image location in the thread from the album, and then reopening it from the thread to download, works fine.

It crashes using both the swipe down gesture and the dedicated download button.

If I download an individual image from the album batch download that's already in the folder it also crashes, but strangely if I select that same duplicate image along with another one it doesn't crash but just ignores the duplicate instead of downloading it again.

Crash log:

=== LOGS(January 8, 2022 3:05:14 PM UTC) ===
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to NONE
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
D/Kuroba-dev | WakeManager: Alarm trigger @ Jan 8, 2022 10:03:06 AM
D/Kuroba-dev | WakeManager: Early; previous @ Jan 8, 2022 9:55:21 AM
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to NONE
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
D/Kuroba-dev | WakeManager: Alarm trigger @ Jan 8, 2022 10:03:19 AM
D/Kuroba-dev | WakeManager: Early; previous @ Jan 8, 2022 9:55:21 AM
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to NONE
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
D/Kuroba-dev | WakeManager: Alarm trigger @ Jan 8, 2022 10:03:47 AM
D/Kuroba-dev | WakeManager: Early; previous @ Jan 8, 2022 9:55:21 AM
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to NONE
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
D/Kuroba-dev | WakeManager: Alarm trigger @ Jan 8, 2022 10:03:51 AM
D/Kuroba-dev | WakeManager: Early; previous @ Jan 8, 2022 9:55:21 AM
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to NONE
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
D/Kuroba-dev | WakeManager: Alarm trigger @ Jan 8, 2022 10:04:09 AM
D/Kuroba-dev | WakeManager: Early; previous @ Jan 8, 2022 9:55:21 AM
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | ImageSaveTask: ImageSaveTask.run() destination = /storage/emulated/0/Download/4chan/v/584241192_Just_finished_EDF_5_and_loved_it,_are_the_other_ga/EARTH-DEFENSE-FORCE-5_20181201174954-1024x576.png
D/Kuroba-dev | ImageSaver: imageSaveTaskFinished imageUrl = https://i.4cdn.org/v/1641653446XXX.png
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.UnsupportedOperationException
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.AlbumViewController.getPostForPostImage(AlbumViewController.java:151)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.appendAdditionalSubDirectories(ImageViewerController.java:313)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveShare(ImageViewerController.java:281)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveImage(ImageViewerController.java:416)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onSwipeToSaveImage(ImageViewerPresenter.java:472)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.onSwipeToSaveImage(MultiImageView.java:277)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.swipeToSaveOrClose(MultiImageViewGestureDetector.kt:153)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.onSwipedBottom(MultiImageViewGestureDetector.kt:114)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.onFling(MultiImageViewGestureDetector.kt:86)
E/Kuroba-dev | UNCAUGHT: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:812)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.lambda$setBitImageFileInternal$7(MultiImageView.java:645)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.lambda$setBitImageFileInternal$7$MultiImageView(Unknown Source:0)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.-$$Lambda$MultiImageView$p_zmqta19ShjEJdgLaF0NmBPp64.onTouch(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.dispatchTouchEvent(View.java:15195)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
E/Kuroba-dev | UNCAUGHT: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
E/Kuroba-dev | UNCAUGHT: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.dispatchPointerEvent(View.java:15458)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
E/Kuroba-dev | UNCAUGHT: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
E/Kuroba-dev | UNCAUGHT: 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:206)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 30
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-34a61da1
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-G781U1

=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.UnsupportedOperationException
	at com.github.adamantcheese.chan.ui.controller.AlbumViewController.getPostForPostImage(AlbumViewController.java:151)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.appendAdditionalSubDirectories(ImageViewerController.java:313)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveShare(ImageViewerController.java:281)
	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveImage(ImageViewerController.java:416)
	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onSwipeToSaveImage(ImageViewerPresenter.java:472)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.onSwipeToSaveImage(MultiImageView.java:277)
	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.swipeToSaveOrClose(MultiImageViewGestureDetector.kt:153)
	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.onSwipedBottom(MultiImageViewGestureDetector.kt:114)
	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.onFling(MultiImageViewGestureDetector.kt:86)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:812)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.lambda$setBitImageFileInternal$7(MultiImageView.java:645)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.lambda$setBitImageFileInternal$7$MultiImageView(Unknown Source:0)
	at com.github.adamantcheese.chan.ui.view.-$$Lambda$MultiImageView$p_zmqta19ShjEJdgLaF0NmBPp64.onTouch(Unknown Source:2)
	at android.view.View.dispatchTouchEvent(View.java:15195)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
	at android.view.View.dispatchPointerEvent(View.java:15458)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Download, SAF location: content://com.android.externalstorage.documents/tree/primary%3ADownload, active: Java API
Phone layout mode: AUTO
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true

**Comment by Adamantcheese** [comment] 2022-01-09 07:59
Duplicate of #1349.

**Closed as completed by Adamantcheese** 2022-01-09 07:59 UTC
Labels: duplicate
