### ISSUE TITLE
Crash report " java.lang.ArrayIndexOutOfBoundsException: length=2; index=2"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1303] opened 2021-07-10 17:55 UTC
Crash report
UUID: 61ff019bfc9a18e931cc1d695cfb4107
Build flavor: dev
Version name: v4.13.6-350665f
OS info: Android 7.1.2, sdk version: 25
Report description: No title
Logs:
```
=== LOGS(10 July 2021 15:24:12 UTC) ===
D/Kuroba-dev | Dependency Injection: Report manager
D/Kuroba-dev | Dependency Injection: Database helper
D/Kuroba-dev | Dependency Injection: Database site manager
D/Kuroba-dev | Dependency Injection: Site repository
D/Kuroba-dev | Dependency Injection: Database board manager
D/Kuroba-dev | Dependency Injection: Board repository
D/Kuroba-dev | Dependency Injection: Board manager
D/Kuroba-dev | SiteModel: Config: null, Settings: {
D/Kuroba-dev | SiteModel:   "settings": {}
D/Kuroba-dev | SiteModel: }
D/Kuroba-dev | SiteModel: Config: null, Settings: {
D/Kuroba-dev | SiteModel:   "settings": {}
D/Kuroba-dev | SiteModel: }
D/Kuroba-dev | Dependency Injection: Database filter manager
D/Kuroba-dev | Dependency Injection: Filter engine
D/Kuroba-dev | Dependency Injection: Database loadable manager
D/Kuroba-dev | Dependency Injection: Database pin manager
D/Kuroba-dev | Dependency Injection: Watch manager
D/Kuroba-dev | Dependency Injection: Site resolver
D/Kuroba-dev | Dependency Injection: Filter watch manager
D/Kuroba-dev | Dependency Injection: Database hide manager
D/Kuroba-dev | Dependency Injection: Database saved reply manager
D/Kuroba-dev | BoardRepository: updateAvailableBoardsForSite changed = false
D/Kuroba-dev | BoardRepository: updateAvailableBoardsForSite changed = false
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
E/Kuroba-dev | UNCAUGHT: 	at java.util.Arrays$ArrayList.get(Arrays.java:3854)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.SiteSetupController.showSettings(SiteSetupController.java:105)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.SiteSetupPresenter.<init>(SiteSetupPresenter.java:36)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.SiteSetupController.<init>(SiteSetupController.java:55)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BrowseController.loadSiteSetup(BrowseController.java:307)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.BrowsePresenter.onBoardsFloatingMenuSiteClicked(BrowsePresenter.java:78)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BrowseController.onSiteClicked(BrowseController.java:177)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu.itemClicked(BrowseBoardsFloatingMenu.java:188)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu.access$400(BrowseBoardsFloatingMenu.java:77)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu$SiteViewHolder.lambda$bind$0(BrowseBoardsFloatingMenu.java:431)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu$SiteViewHolder.lambda$bind$0$BrowseBoardsFloatingMenu$SiteViewHolder(BrowseBoardsFloatingMenu.java)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.-$$Lambda$BrowseBoardsFloatingMenu$SiteViewHolder$EUqFIMtDTzVAsQXnE3FViMVwo74.onClick(lambda)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.performClick(View.java:5647)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:22462)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:754)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:163)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6205)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 25
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-350665f
E/Kuroba-dev | UNCAUGHT: Phone Model: Xiaomi Redmi 4X


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Clover, SAF location: , active: Java API
Phone layout mode: AUTO
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by Adamantcheese** [comment] 2021-07-10 20:46
Duplicate of #1301. Someone hasn't updated.

**Closed as completed by Adamantcheese** 2021-07-10 20:46 UTC
Labels: duplicate
