### ISSUE TITLE
Tapping an image with immersive mode makes the thread go up and the bookmarked threads scroll to the top

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#710] opened 2020-02-23 16:12 UTC
UUID: 79372dd02fb3dc6243631c83509f5a8a
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: Everytime you open an image in immersive mode the thread goes up instead of going back to its original position. Not only that but the bookmarked threads section scrolls right back to the top, this is specially a problem if you have a lot of threads bookmarked.

**Comment by Adamantcheese** [comment] 2020-02-23 23:30
I can't reproduce the thread scrolling to top, and the drawer doesn't scroll, it's just shifting its location because the top/bottom decor views are coming back into existence, shifting everything by their heights.

**Comment by Adamantcheese** [comment] 2020-07-10 05:01
Gonna close this, no additional reports of it occurring and it being open for this long... I don't see this ever being fixed. Probably that strange shift-post format issue that occurs on some devices where the recycler view layout manager just decides to reset itself completely.

**Closed as completed by Adamantcheese** 2020-07-10 05:01 UTC
Labels: bug, cantrepro, report/crash report
