### ISSUE TITLE
Crash: Drag shadow dimensions must be positive

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1150] opened 2020-11-08 13:36 UTC
```E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.IllegalStateException: Drag shadow dimensions must be positive
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.startDragAndDrop(Unknown Source:480)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.Editor.startDragAndDrop(Unknown Source:47)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.Editor.performLongClick(Unknown Source:76)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.TextView.performLongClick(Unknown Source:22)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.performLongClick(Unknown Source:4)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View$CheckForLongPress.run(Unknown Source:37)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Unknown Source:244)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(Unknown Source:101)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)

**Comment by Adamantcheese** [comment] 2020-11-08 20:49
Duplicate of #700, but as of time of writing, that same Wordpress issue has been resolved with a rather good writeup of how it happens. I can exactly reproduce this issue when trying to drag and drop a single newline, so uh don't do that?

**Closed as completed** 2020-11-09 00:47 UTC
Labels: bug
