### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#635] opened 2020-02-12 07:47 UTC
UUID: 6adea4f7bb48db487a361e12d29d6aa1
Build flavor: dev
Version name: v4.11.0-b7b5bb2
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
Called from unhandled exception handler.
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.view.ViewConfiguration.get(ViewConfiguration.java:491)
	at android.view.View.<init>(View.java:5440)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.getActiveView(MultiImageView.java:210)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.toggleTransparency(MultiImageView.java:670)
	at com.github.adamantcheese.chan.ui.view.MultiImageView$2.onSuccess(MultiImageView.java:376)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:669)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:42)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$resultHandler$1$1.run(FileCacheV2.kt:800)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7807)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```

**Comment by K1rakishou** [comment] 2020-02-12 07:47
I think I've already created an issue for this crash but couldn't find it.

**Comment by Adamantcheese** [comment] 2020-02-12 07:56
Duplicate of #633.

**Closed as completed by Adamantcheese** 2020-02-12 07:56 UTC
Labels: bug, duplicate, report/crash report
