### ISSUE TITLE
post deletion dialog completely transparent

### ISSUE THREAD

**Issue by yokodake** [Adamantcheese/Kuroba#1114] opened 2020-10-09 10:51 UTC
The confirmation dialog for deleting a post is entirely transparent.
It's hard to see the confirmation buttons. as well as the `Only delete post Image` checkbox.

**Comment by Adamantcheese** [comment] 2020-10-09 20:38
Duplicate of #1018.

**Closed as completed by Adamantcheese** 2020-10-09 20:38 UTC
Labels: duplicate
