### ISSUE TITLE
[MEMORY LEAK] StartActivity is leaking via Snackbar

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#583] opened 2020-02-07 11:15 UTC
```
ApplicationLeak(className=com.github.adamantcheese.chan.StartActivity, leakTrace=
┬
├─ android.view.accessibility.AccessibilityManager
│    Leaking: NO (a class is never leaking)
│    GC Root: System class
│    ↓ static AccessibilityManager.sInstance
│                                  ~~~~~~~~~
├─ android.view.accessibility.AccessibilityManager
│    Leaking: UNKNOWN
│    ↓ AccessibilityManager.mTouchExplorationStateChangeListeners
│                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
├─ android.util.ArrayMap
│    Leaking: UNKNOWN
│    ↓ ArrayMap.mArray
│               ~~~~~~
├─ java.lang.Object[]
│    Leaking: UNKNOWN
│    ↓ array Object[].[0]
│                     ~~~
├─ androidx.core.view.accessibility.AccessibilityManagerCompat$TouchExplorationStateChangeListenerWrapper
│    Leaking: UNKNOWN
│    ↓ AccessibilityManagerCompat$TouchExplorationStateChangeListenerWrapper.mListener
│                                                                            ~~~~~~~~~
├─ com.google.android.material.snackbar.BaseTransientBottomBar$SnackbarBaseLayout$1
│    Leaking: UNKNOWN
│    Anonymous class implementing androidx.core.view.accessibility.AccessibilityManagerCompat$TouchExplorationStateChangeListener
│    ↓ BaseTransientBottomBar$SnackbarBaseLayout$1.this$0
│                                                  ~~~~~~
├─ com.google.android.material.snackbar.Snackbar$SnackbarLayout
│    Leaking: YES (View.mContext references a destroyed activity)
│    mContext instance of android.view.ContextThemeWrapper, wrapping activity com.github.adamantcheese.chan.StartActivity with mDestroyed = true
│    View#mParent is null
│    View#mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 0
│    ↓ Snackbar$SnackbarLayout.mContext
├─ android.view.ContextThemeWrapper
│    Leaking: YES (Snackbar$SnackbarLayout↑ is leaking and ContextThemeWrapper wraps an Activity with Activity.mDestroyed true)
│    ↓ ContextThemeWrapper.mBase
╰→ com.github.adamantcheese.chan.StartActivity
​     Leaking: YES (ContextThemeWrapper↑ is leaking and Activity#mDestroyed is true and ObjectWatcher was watching this)
​     key = b8b2fd2e-3856-4a97-832b-210cbd865a30
​     watchDurationMillis = 5273
​     retainedDurationMillis = 266
, retainedHeapByteSize=360113)
```

**Comment by Adamantcheese** [comment] 2020-02-07 11:24
Duplicate of #581. See item 2 in there.

**Closed as completed by Adamantcheese** 2020-02-07 11:24 UTC
Labels: duplicate

**Comment by K1rakishou** [comment] 2020-02-07 11:28
Oh, didn't notice that, alright.
